### ISSUE TITLE
Further clarify `register_tx`/`register_output` distinction in docs

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1069]
See https://github.com/getlipa/ldk-sample-java/pull/1#discussion_r690384571 for a concrete suggestion, but it seems there continues to be some confusion from users over the distinction here.

**Comment by gabbyprecious** [comment]
Hi @ConorOkus is this available to work on?

**Comment by ConorOkus** [comment]
Yes sure @gabbyprecious

**Comment by tnull** [comment]
Will pick this up.

**Comment by tnull** [comment]
> Will pick this up.

Ah, I'm just seeing that @gabbyprecious indicated in #1395 that she intends to finish this. Holing off for now.
