### ISSUE TITLE
Reconsider `user_channel_id`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1125]
I don't think any users actually use this, and because you can't do anything with it for inbound channels its much less useful than it could be. Worse, we don't expose it in a few places we really should if we want users to use it.

Maybe we should drop it entirely, maybe we should double-down on it, with it included in more places and the ability to set it for inbound channels (and probably reject channels before we send the `AcceptChannel` message).

**Comment by tnull** [comment]
Seems we doubled-down on it, e.g., in LDK Lite? So can we close this?
