### ISSUE TITLE
Need to support decoding more onion types

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1129]
I received an onion failure after an MPP part timed out which log reported as unknown, i presume we're just out of date compared to BOLTs:

`2021-10-17 20:33:13.537 WARN  [lightning::ln::onion_utils:484] Onion Error[from ...: (0x17)] Unknown`

**Comment by dunxen** [comment]
I presume that was `mpp_timeout`? I think I will be able to tackle this. Will also get me more familiar with onion messages in the spec. Probably are a few other new ones we're missing support for.

**Comment by TheBlueMatt** [comment]
Yep, the correct type would have been mpp_timeout here. Indeed, I wouldn't be surprised if there were others.
