### ISSUE TITLE
Add explicit "no inbound channels accepted" flag in config

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1135]
Users can currently approximate "I refuse all inbound channels" by doing something like setting `ChannelHandshakeLimits::min_funding_satoshis` in `UserConfig::peer_channel_config_limits` to something greater than 21 million BTC, but ideally we'd just have a simpler flag users can set instead.

Note that users today can always change their default-inbound config by setting `ChannelManagerReadArgs::default_config` to anything they want.

**Comment by TheBlueMatt** [comment]
On second thought, when we do this, we should just have a setting to kick the decision out via an event. That would give the user some kind of "someone is asking to open a channel, peer id is X, value is Y" event and then let users either say yes or no.

**Comment by tnull** [comment]
The config option to disallow incoming channels should be addressed by #1173.

Regarding the second part, i.e., yielding an event and awaiting user input I'm not yet entirely sure where/how long to store the pending inbound `OpenChannel` messages and how to handle them, for example, if the user does not react at all/in time. This could require some logic akin to c-lightning's hooks. However, the question then is whether introducing this kind of complexity is warranted given the use case?

**Comment by vincenzopalazzo** [comment]
This was fixed by https://github.com/lightningdevkit/rust-lightning/pull/1173/files?

**Comment by TheBlueMatt** [comment]
Yes, the immediate issue here was fixed. I've moved the "part 2" to #1242.
