### ISSUE TITLE
Sanity Check KeysInterface on ChannelManager Deserialization

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1174]
If the KeysInterface provided to the ChannelManager is generating different keys from what we had before being written, we need to fail, not try to run.

**Comment by TheBlueMatt** [comment]
Also on ChannelMonitors in and `spend_spendable_outputs`

**Comment by vss96** [comment]
@TheBlueMatt Hey I would like to pick this up. Can you guide me a little as to which modules I'll have to explore to fix the same issue? Will the sanity check happen when a new object for the ChannelManager is created?

**Comment by TheBlueMatt** [comment]
I think there's two parts to this:

1) a) In the impl `Writeable for ChannelManager<Signer, M, T, K, F, L>` block, in the `write_tlv_fields` macro call, store a new (odd, option) field containing the `self.our_network_pubkey` object.
    b) In the impl `ReadableArgs<ChannelManagerReadArgs<'a, Signer, M, T, K, F, L>> for (BlockHash, ChannelManager<Signer, M, T, K, F, L>)` block, in the `read_tlv_fields!()` macro call, load the same field, and, if set, compare it to the calculated `our_network_pubkey` value, returning an `InvalidValue` err if it does not match (after calling `log_error!()` with some error message).
2) a) In `KeysManager::spend_spendable_outputs`, when we derive a static key in `SpendableOutputDescriptor::StaticOutput` handling, we should compare that key with the expected value (currently we only compare once and assume the key we should use is the "other" of the two options, instead of always checking).
    b) In `InMemoryChannelKeys`'s `sign_counterparty_payment_input` and `sign_dynamic_p2wsh_input` methods, the expected input script_pub_key should be compared with the script in `DelayedPaymentOutputDescriptor` and `StaticPaymentOutputDescriptor`'s `output` fields.

**Comment by vss96** [comment]
@TheBlueMatt I have raised a pr which addresses 1a, 1b, and 2b.

>  In KeysManager::spend_spendable_outputs, when we derive a static key in SpendableOutputDescriptor::StaticOutput handling, we should compare that key with the expected value (currently we only compare once and assume the key we should use is the "other" of the two options, instead of always checking)

 Regarding 2a: initially, there is a check for the output's script_pubkey and either 1 or 2 is assigned to the derivation_idx.  
What does "always checking" mean in this context? If the scripts are not equal, do we panic! at that spot?
And if they are equal do we assign derivation_idx=1 and continue?

**Comment by TheBlueMatt** [comment]
> Regarding 2a: initially, there is a check for the output's script_pubkey and either 1 or 2 is assigned to the derivation_idx.

The check isn't really "1 or 2", though, its "does it match 1? no, okay, assume 2" - we never actually check that it matches 2.
