### ISSUE TITLE
Explore making more in-depth fee breakdowns accessible from Route object

### ISSUE THREAD

**Issue by ConorOkus** [lightningdevkit/rust-lightning#1193]

**Comment by TheBlueMatt** [comment]
I'm not sure what this refers to?

**Comment by ConorOkus** [comment]
@arik-so any insight into this? Let's close if not.

**Comment by arik-so** [comment]
I'm sorry, what's the context of this issue?

**Comment by ConorOkus** [comment]
Added this from our notes from one of the code reviews we did recently just in case anyone could remember, I can't remember the context for this one so let's close.
