### ISSUE TITLE
Log penalty info in route-success line

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1233]
When we find a route we print info about it, we should include penalty information when we do so.

**Comment by jurvis** [comment]
hi @TheBlueMatt 👋, I started looking at this issue and I was wondering, what is the desired output for the penalties? Do we want to display them per-hop, per-path, or per-route?

My inclination is to add a `path_penalty_msat` field to `RouteHop`, which will basically enable us to log penalties at any level if we wanted to. However, I'm wondering if there are any downsides to that implementation. Let me know what you think!

**Comment by TheBlueMatt** [comment]
We currently log each hop in each path that we select as a candidate while routing. I think we should list the penalty that we assigned to each hop when we do so. I'd generally prefer to not add a new field in `RouteHop` to do so, though, especially given we already track the `path_penalty_msat`, which is the total across a few hops. If its easier, we can always just log the full path penalty, and its not hard for someone reading the logs to do some math and figure out the per-hop values :).

**Comment by jurvis** [comment]
@TheBlueMatt sounds good -- thanks for clarifying! I think I have an idea of what to do now.

> especially given we already track the `path_penalty_msat`, which is the total across a few hops. 
correct me if I'm wrong, but that means that `path_penalty_msat` does behave like `fee_msat`? i.e. the last hop will be the full path penalty?

**Comment by TheBlueMatt** [comment]
> correct me if I'm wrong, but that means that path_penalty_msat does behave like fee_msat? i.e. the last hop will be the full path penalty?

Yes.

**Comment by jurvis** [comment]
^ took a stab at this issue, let me know if I'm barking up the right tree 😄

**Comment by jurvis** [comment]
hey @TheBlueMatt, I'm working on customizing the debug output for `PathBuildingHop`. 

I'm wondering, which fields do we want to print, if we were to clean it up?

**Comment by jurvis** [comment]
@TheBlueMatt sounds good -- I'll start with logging those for now and we can go from there!

**Comment by jurvis** [comment]
@TheBlueMatt sorry I took awhile to make such a small change, but I just put up the PR with the most trivial approach to cleaning up the output. I also posted a question related to the ergonomics of the print-out, and will love your thoughts.

**Comment by jkczyz** [comment]
Fixed by #1318.
