### ISSUE TITLE
Send peers the remote IP we see on the connection

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1244]
We should implement the BOLT spec change from https://github.com/lightning/bolts/pull/917. Its a bit tricky with our architecture since we don't manage the TCP sockets ourselves, but we can just have the user provide the address in the connection-accepted/connection-made calls into `PeerHandler` and go from there.

**Comment by Psycho-Pirate** [comment]
I would like to work on this. Please tell me where should I start?

**Comment by Psycho-Pirate** [comment]
> 

What will be the data type of `NetworkAddress`? Also do you want me to name the variable as `NetworkAddress` or something like `their_Network_Address` inside the `Peer` struct.

**Comment by TheBlueMatt** [comment]
Sorry, I meant `NetAddress` (which is already a thing), not `NetworkAddress`.
