### ISSUE TITLE
Include htlc_maximum/minimum in ChannelDetails

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1287]
This is useful in the router and we should also pass it as described at https://github.com/lightningdevkit/rust-lightning/pull/1199#discussion_r793922464

**Comment by BennyBlockchain** [comment]
Should getting the minimum htlc value be `get_holder_htlc_minimum_msat` or `get_counterparty_htlc_minimum_msat`?

For routing it should be the counterparty's minimum htlc value correct?

**Comment by TheBlueMatt** [comment]
> For routing it should be the counterparty's minimum htlc value correct?

**Comment by BennyBlockchain** [comment]
So in ChannelDetails we would want both holder & counterparty min/max?

API doesn't implement max htlc for counterparty and holder for `Channel` struct. It just implements the max by taking the minimum of `self.channel_value_satoshis * 1000 * 9 / 10` and `holder_max_htlc_value_in_flight_msat` in `get_announced_htlc_max_msat`

**Comment by TheBlueMatt** [comment]
Oops, sorry I took a while to get back to you here, I'll continue discussion on the PR, thanks!

**Comment by TheBlueMatt** [comment]
Sounds great.
