### ISSUE TITLE
Fix (+test) phantom node onion error returning

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1308]
See https://github.com/lightningdevkit/rust-lightning/pull/1199#discussion_r806303997 and the following comment, probably need to test al the cases where we return onion errors in that function. Also some nits worth hitting at https://github.com/lightningdevkit/rust-lightning/pull/1199#pullrequestreview-882275581

**Comment by jkczyz** [comment]
Also want to tag module-level docs for follow up, but wouldn't mind leaving for a more general documentation clean-up. https://github.com/lightningdevkit/rust-lightning/pull/1199#pullrequestreview-879146797
