### ISSUE TITLE
Use #ZeroBaseFee for more efficency

### ISSUE THREAD

**Issue by pud-micha** [lightningdevkit/rust-lightning#1336]
Hello,

you should set

forwarding_fee_proportional_millionths: 11,
forwarding_fee_base_msat: 0

in /src/util/config.rs

As described here
https://lnrouter.app/graph/zero-base-fee
and here
https://arxiv.org/abs/2107.05322
the base fee is a real problem in pathfinding. There are many open channels in the field. But if you can only open a new channel without a base fee then over time every channel will have none and the network is as efficient as possible.

Most people do not change default settings. So these setting should be the best possible for the network.

:)

**Comment by TheBlueMatt** [comment]
It's not true that setting no base fee is "more efficient", and it may be detrimental to the node operator.

**Comment by pud-micha** [comment]
So it is not true that zero base fee downgrades a NPC to only P or NP? And how do you know that node operators dislike a percentage fee? Are there any polls about that? Just by saying "it is not true" it does not make it true. Pickhardt et al. has mathematical and reviewed proof. Is his proof and the reviewers maths wrong or is it just an opinion of yours? Please add a link to a published reviewed paper that shows the mistakes in his.

**Comment by TheBlueMatt** [comment]
Not sure what "NPC" here means, but it is definitely not true that zero base fee somehow makes routing more efficient. It does allow people to use other routing algorithms which may or may not be better than heuristics approaches which approximate them. Not to mention such other algorithms aren't inherently "better", but instead optimize for something different than existing algorithms, whether that's the correct thing to optimize for or not depends on users.
