### ISSUE TITLE
lightning-0.0.104 fails to compile on Rust 1.60 beta due to ambiguous `fmt` call in `ln/msgs.rs`

### ISSUE THREAD

**Issue by the8472** [lightningdevkit/rust-lightning#1344]
A crater run found that the crate no longer compiles on Rust 1.60 beta (see https://github.com/rust-lang/rust/issues/94507) due to a newly added trait impl in the standard library causes ambiguities in method resolution.

The regression has been deemed an acceptable minor change per [RFC 1105](https://rust-lang.github.io/rfcs/1105-api-evolution.html).
It can be fixed by using [fully qualified function call syntax](https://doc.rust-lang.org/reference/expressions/call-expr.html#disambiguating-function-calls) to disambiguate the `fmt` call.

**Comment by TheBlueMatt** [comment]
Yes, we tried to open an issue upstream at https://github.com/rust-lang/rust/issues/93599 and report it some time ago, see discussion there.

**Comment by the8472** [comment]
Hah, I even commented there. Sorry for the noise as you already were aware.

**Comment by TheBlueMatt** [comment]
All good, not your job to map names to projects.
