### ISSUE TITLE
Create a LDK node connection QR code format

### ISSUE THREAD

**Issue by Bosch-0** [lightningdevkit/rust-lightning#1345]
Hello,

It would be handy if their was a simple way to connect to an LDK node by scanning a QR code, similar to LND connect and the WIP by @opnoms [here](https://github.com/ZeusLN/zeus/issues/515) for C-lightning. 

[Eclair issue](https://github.com/ACINQ/eclair/issues/2199)

**Comment by TheBlueMatt** [comment]
Hmm, I don't think this kind of thing belongs in LDK - LDK is not a lightning node itself, but a toolkit to build a custom lightning node with any features you want. Our API already exposes enough information to construct such a QR code, and it's up to LDK users (ie the authors of node software) if such a feature makes sense to them.
