### ISSUE TITLE
Grind signatures to low-r value

### ISSUE THREAD

**Issue by devrandom** [lightningdevkit/rust-lightning#1387]
It would be nice to have rust-lightning grind signatures to low-r value, possibly controlled by a feature gate.  This makes the tx weight more predictable.  Otherwise, there's a 50% chance for each signature to have an extra byte to represent the sign.

**Comment by moneyball** [comment]
Does this utility exist in rust-bitcoin?

**Comment by moneyball** [comment]
did ldk have a direct dependency on libsecp previously? does it now? (i assume rust-bitcoin handled this?)

**Comment by devrandom** [comment]
rust-bitcoin re-exports rust-libsecp, which is what lightning is and was using for signing ops.  so no dependency changes, just another function.
