### ISSUE TITLE
Expose more info in `PaymentForwarded`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1391]
When this was added I figured we should be conservative to avoid users logging exact forwarding history (this is bad for network-wide privacy!) but that doesn't mean important info isn't missing from them that users will want. Ultimately I think we have to air on the side of features, not privacy, sadly - while we shouldn't bother to include the payment hash, I think, we should include things like the source + sink nodes/channels in the event.

**Comment by atalw** [comment]
Do we want the source key to be a `PublicKey` type or `HTLCSource` type? Don't have easy access to data for both so I think we'll have to move things around a bit. Also could you please elaborate a little on what sink nodes and sink channels are?

**Comment by TheBlueMatt** [comment]
No, `HTLCSource` is an internal type with a bunch of additional data and cryptographic material we need to fail backwards. We'll want to use a `PublicKey` and/or channel id (as a `[u8; 32]`) maybe both.

**Comment by keyuebao** [comment]
Having a channel id here would be super helpful 👍

**Comment by 0xcodeboi** [comment]
If no one is already working on this, I'd like to take this on. I can probably have this completed by next weekend.

<details>
  <summary>Notes for self</summary>
  Event is described here
https://github.com/lightningdevkit/rust-lightning/blob/7671ae54522197dbca495c4c7b3fec5c814a1841/lightning/src/util/events.rs#L343-L363

and at quick glance, the references to update are
https://github.com/lightningdevkit/rust-lightning/blob/7671ae54522197dbca495c4c7b3fec5c814a1841/lightning/src/util/events.rs#L523-L528
and
https://github.com/lightningdevkit/rust-lightning/blob/7671ae54522197dbca495c4c7b3fec5c814a1841/lightning/src/util/events.rs#L684-L695
and
https://github.com/lightningdevkit/rust-lightning/blob/6b8ad4ec33eb4f90395aac21c56c804b0b6c9429/lightning/src/ln/channelmanager.rs#L4295-L4298

There's also tests, mostly calling this macro
https://github.com/lightningdevkit/rust-lightning/blob/7671ae54522197dbca495c4c7b3fec5c814a1841/lightning/src/ln/functional_test_utils.rs#L1330-L1342
</details>

**Comment by atalw** [comment]
I've been working on this and am nearing completion. There is one bug (unexpected behaviour?) which is causing a few tests to fail so maybe you could help out. Please refer to these comments:
[Comment one](https://github.com/atalw/rust-lightning-1/commit/8107f9b719e11f3c4c7c54acdf4667a033679d81#r70282911) 
[Comment two](https://github.com/atalw/rust-lightning-1/commit/8107f9b719e11f3c4c7c54acdf4667a033679d81#r70283355)

**Comment by TheBlueMatt** [comment]
We should still expose the destination/sink channel id, #1419 only exposed the source.

**Comment by atalw** [comment]
I'll add that next!

**Comment by TheBlueMatt** [comment]
You may want to take a look at #1231, which had actually implemented that half as well, but wasn't actively being worked on. Should be able to copy a bunch of that work.
