### ISSUE TITLE
Expose a `PaymentForwardingFailed` Event

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1392]
When we try to forward a payment but it fails, users may want to know about this, as it may imply something about rebalancing channels or at least may be something users want to collect stats about. As discussed in #1391 I don't think we want to expose payment hash here, but source + sink channels+nodes and whether we forwarded at all or failed without being able to forward would be useful info for users.

**Comment by jurvis** [comment]
I can take a stab at this.

Just a couple of questions:
1. Is the sink node and channel referring to the node we are forwarding to that failed and the outbound channel respectively?
2. Same question as above, but for source node/channel
3. Will adding an `else` case [here](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channelmanager.rs#L4287-L4299) suffice in capturing where forwarding logic can fail? (still new to code base, just making sure I'm understand what is happening correctly)

**Comment by TheBlueMatt** [comment]
Sorry for the delay here.

> Sink + source?

Yes, correct, I was using it to refer to the forwardee and HTLC source.

> Will adding an else case [here](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channelmanager.rs#L4287-L4299) suffice in capturing where forwarding logic can fail? (still new to code base, just making sure I'm understand what is happening correctly)

Ah, no, sorry, I believe that branch is for if the claim is duplicative of a previous claim (which can happen sometimes). For the forwarding-failed case you probably want to look at `fail_htlc_backwards_internal`.

**Comment by valentinewallace** [comment]
I think this was closed by #1403
