### ISSUE TITLE
default to using new onion tlvs even without feature flags

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1393]
Everyone is moving towards requiring TLV onions, so we should really be defaulting to them, especially when we only have route hints and no features for a node.

**Comment by ViktorTigerstrom** [comment]
I could pick this one up if no one else is working on it!

Is the general issue that we default to the BOLT 4 legacy hop_data payload format here if when there are no node features?
https://github.com/lightningdevkit/rust-lightning/blob/44c0374ae6c8ba92d978d8b0adc75ca9de96ee0d/lightning/src/ln/onion_utils.rs#L136

Given the discussion in the latest LDK dev meeting, do we just want to drop creating `msgs::OnionHopDataFormat::Legacy` payloads all together in this function, or is there a scenario where we'd still like to create them?
