### ISSUE TITLE
Include expiry in invoices

### ISSUE THREAD

**Issue by jkczyz** [lightningdevkit/rust-lightning#1411]
When creating an `Invoice` using functions in the `lightning-invoice` crate's `utils` module, the invoice expiration is not set. It should be set with the value encoded in the provided payment secret. Otherwise, BOLT 11 defines the default expiry to be 1 hour whereas `ChannelManager` will use whatever value is encoded in the payment secret.

This may be tricky because either the methods will need to take in a `ChannelManager` to verify the payment secret and extract the expiry or the expiry needs to be passed in but could potentially not match what's encoded in the payment secret.

**Comment by dunxen** [comment]
I can try pick this up. Would be some alright exposure to `lightning-invoice` crate :)

**Comment by jkczyz** [comment]
Great! Also, note that his only is a problem for `create_phantom_invoice` and `create_phantom_invoice_with_description_hash`. The other utility functions take a `ChannelManager` and use `DEFAULT_EXPIRY_TIME`.

**Comment by dunxen** [comment]
Seems only the second option would make sense in this case as requiring a `ChannelManager` would defeat the purpose of #1384 😅. However, then we are stuck with the possibility of the expiry not matching what's encoded as you mentioned.

**Comment by TheBlueMatt** [comment]
I don't think at need to worry about the expiry not being encoded properly - you can't use phantom nodes without it so if the expiry isn't encoded correctly we should be erroring anyway. Does seem like this needs to be based on #1384.

**Comment by jkczyz** [comment]
We may want to consider having the phantom invoice utility functions directly call the exposed creation functions from #1384 instead of exposing functions for decoding. Then the interface would more closely match the non-phantom invoice utility functions.

**Comment by TheBlueMatt** [comment]
Adding to 107 cause it's an oversight we should fix, but if it slips no big deal.

**Comment by dunxen** [comment]
I see #1384 is merged so will get back to work on this. Spread myself a bit thin with the Qala.dev stuff 🥲

**Comment by jkczyz** [comment]
Re-opening since while #1422 added an `invoice_expiry_delta_secs` to the utility functions, it didn't set expiry on the `Invoice` itself. Also, we should allow passing `invoice_expiry_delta_secs` to the non-phantom utilities for those not wanting the implicit default expiry.

**Comment by dunxen** [comment]
Will fix today.
