### ISSUE TITLE
Explore replacing BTreeSet in IndexedMap with a sorted Vec

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1473]
We currently use a `BTreeMap` for storing network graph data, as we need to be able to access it starting from a given key and continue iteration. This makes a sorted KV store like a BTree the obvious choice, but we don't actually need the keys to be sorted, we just need them to not change order as we iterate the graph.

Technically we also need to be able to check if a new key is below some previous iteration that is in-progress.

Supposedly the `indexmap` crate may offer something like what we need, but ultimately any hashtable that doesn't ever re-hash should suffice, and while creating our own probably won't be as efficient as hashbrown, it'd probably still be faster than a btree, and use way less memory compared to the substantial heap fragmentation that a btree creates.

**Comment by dunxen** [comment]
> Building our own HashMap is probably the first rabbit hole to go down, but that will need to be relatively carefully benchmarked.

Happy to start going down this rabbit hole :)

**Comment by G8XSU** [comment]
Requirement clarification : 
I understand that on-insert/rehash, we want to complete ongoing iteration in some order just to cover all keys(existing) and not cover duplicate keys. 

But how important is it to also iterate through newly added key in ongoing iteration ? 
Is it just good to have? Or a necessary requirement to cover the newly added key.
