### ISSUE TITLE
Allow specifying retry strategy per-payment instead of globally

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1487]
Probably should have thought of this before #1418, but oh well - ideally we'd be able to specify the payment retry count on a per-payment basis rather than globally in the InvoicePayer. This would likely imply refusing to retry things that weren't started using the InvoicePayer/after restart, but that may be okay? Would have to document that or make it configurable.

**Comment by benthecarman** [comment]
Tried working on this seems, complications will come from `handle_event_internal`. Could simplify by keeping the retry strategy as the default and have the ability to pass an `Option<Retry>` when paying to override

**Comment by valentinewallace** [comment]
Ah, this is being done as a side effect of #1916 and its follow-ups actually. Guess I'll self-assign.

**Comment by SimonAdameit** [comment]
It appears this issue is resolved. Could it be closed, or is there any further clarification needed?

**Comment by valentinewallace** [comment]
> It appears this issue is resolved. Could it be closed, or is there any further clarification needed?

Good point, yes this should be resolved.
