### ISSUE TITLE
Break `ClosureReason::CommitmentTxConfirmed` Up Somewhat

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1488]
If an HTLC times out and we close a channel from the ChannelMonitor, we currently mark the `ClosureReason` as `CommitmentTxConfirmed`, even though the commitment tx has not yet confirmed, not to mention it was us who closed the channel! From a cursory glance, the fix is trivial - just interpret (and maybe rename) `MonitorEvent::CommitmentTxConfirmed` to mean "we force-closed" and then we can think about adding more detail, but I think its literally always due to HTLC timeouts.

**Comment by colinjhicks** [comment]
Hi, is the idea to decide on a more fitting name and replace all uses of CommitmentTxConfirmed with the new name? As well as reinterpret the note on CommitmentTxConfirmed in the Monitor Event enum?

I'm also curious about MonitorEvent::FundingTimedOut. I don't see it used anywhere but it seems more appropriate for HTLC time outs

**Comment by Mirebella** [comment]
Is this still open? Looks like https://github.com/lightningdevkit/rust-lightning/commit/a96e2fe144383ea6fd670153fb895ee07a3245ef commit and https://github.com/lightningdevkit/rust-lightning/pull/2887 in "assesment against linked issues" section might have already addressed it.
