### ISSUE TITLE
Prefer channels with a max_htlc_in_flight < channel capacity

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1515]
In discussions this week, it was noted that channels with an HTLC in-flight-max smaller than the channel capacity (specifically, both directions having an htlc_in_flight_max < 50% of the channel capacity, with lower better) makes a channel somewhat harder to probe for live balances, thereby improving privacy for payments routed through that node.

While more privacy protections should be added, this is a super trivial heuristic that we can use to encourage network-wide "good behavior" today - simply detect this and prefer channels which have this privacy improvement in our scorer.

**Comment by tnull** [comment]
I'll pick this up and might also have a look at some of the other privacy enhancements discussed.
