### ISSUE TITLE
Router allows paths with ~useless value contributions

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1520]
We currently limit MPP sends in channelmanager, somewhat arbitrarily, to 10 paths. This is probably fine, except that the router gets a bit excited finding cheap paths sometimes and generates more than 10 paths for large-ish value payments. An easy fix is probably to change `minimal_value_contribution_msat` to always be at least 10% of the payment amount, even if we've already collected a lot of paths. Alternatively, we could allow the channelmanager to send up to 20 paths, and limit at 5%.

Tentatively assigning @tnull.

**Comment by ddiekroeger** [comment]
i've also seen 40+ path routes recommended
