### ISSUE TITLE
Investigate/improve performance benchmarking in CI

### ISSUE THREAD

**Issue by moneyball** [lightningdevkit/rust-lightning#1537]
1) What do we already measure performance-wise in CI?
2) Do we pay attention to it? (106 might've had a regression? 107 has a massive win...no one noticed until @devrandom)
3) What more could easily be added?

Slack discussion for context https://lightningdevkit.slack.com/archives/CTDGZN1T9/p1654894461383259?thread_ts=1654865456.691709&cid=CTDGZN1T9

**Comment by devrandom** [comment]
if you are asking me, I don't know - I'm a Gitlab fanboi
