### ISSUE TITLE
Send channel_resstablish that causes lnd to force-close if we don't have the channel

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1565]
`lnd` is now the only major lightning implementation that deliberately ignores `error` messages, causing it to not force-close channels even though we ask the peer to. `lnd` themselves works around this when trying to restart with their "static channel backups" (which are not, in fact, channel backups...) by sending a `channel_reestablish` message that is bogus (I don't recall *exactly* how, so would need to dig on that first). As much as I really hate to create yet another workaround in our code just because lnd continues to ignore the common spec that no one else has a problem with, it is kinda important we can make our peer broadcast the latest state if we ask, so we should probably send a similar `channel_reestablish` any time we receive a `channel_reestablish` from a peer for a channel we dont (any longer) have.

**Comment by benthecarman** [comment]
Related to this, would be great if we had a way to give a set of `ChannelMonitor`s and it would send the `channel_resstablish` message to have the channels closed, without needing a channel manager. This would allow ldk to have a version of static channel backups but with more safety.
