### ISSUE TITLE
Copy announcement message addresses into NodeInfo on load

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1630]
On startup, we may deserialize a stored NodeAnnouncement and find new address types that we previously didn't understand. This will leave us with a NodeInfo struct (the obvious place users will look for address information) that has an addresses list that is missing elements.

Additionally, we're storing address information twice in two separate, redundant, heap-allocated structures.

We should address both issues by simply dropping the address list from NodeInfo. The only two gotchas are that we'll want to provide serialization compatibility, and that we'll want to ensure we're liberal in storing NodeAnnouncements as long as they have even a mostly-reasonable excess data size. We should probably take this opportunity to also relay NodeAnnouncments that have more excess data than zero.

**Comment by ssbright** [comment]
Hey, I am new here and would like to start getting involved. I am going to start looking into this issue and see what I can understand.

**Comment by ssbright** [comment]
Apologies for the poor communication. I tried working on this but found that my rust skills were not adequate enough. I will have to start somewhere more simple to learn how to contribute to open source. Hopefully someone else can tackle this issue.
