### ISSUE TITLE
Improve logging of pathfinding behavior

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#1646]
The behavior of sending a payment can be quite confusing to users, in particular if an otherwise obvious channel choice is avoided without giving any feedback as to why. 

We therefore should try to improve the logging in `get_route` without getting too spammy. In particular, we should find a way to give users feedback when for example a direct channel is avoided due to lacking channel reserves, its value contribution, or similar.

**Comment by Lalitmohansharma1** [comment]
Hey i,d like to try this issue.

**Comment by Lalitmohansharma1** [comment]
And i am new to opensource, so i may need guidance.

**Comment by tnull** [comment]
Welcome! The relevant parts of the code can be found in the `get_route` method which is part of `lightning/routing/router.rs`. I'd recommend first reading this method in its entirety to understand how it works (it's kind of a beast, featuring multiple sub-macros, etc).

Then you'll have to figure out for which cases it makes sense to add logging lines (probably in `TRACE` level). It's important to strike a balance here, as a lot of hops/paths are excluded trivially, which shouldn't spam our logs. However, it would be nice to have logging for edge cases, in particular if they result in *no path* being returned at all. So maybe to start you could, instead of just logging any candidate exclusion right away, remember the last failure reason and only log it when it results in no path being returned.

**Comment by Lalitmohansharma1** [comment]
Thanks

**Comment by Lalitmohansharma1** [comment]
> Welcome! The relevant parts of the code can be found in the `get_route` method which is part of `lightning/routing/router.rs`. I'd recommend first reading this method in its entirety to understand how it works (it's kind of a beast, featuring multiple sub-macros, etc).
> 
> Then you'll have to figure out for which cases it makes sense to add logging lines (probably in `TRACE` level). It's important to strike a balance here, as a lot of hops/paths are excluded trivially, which shouldn't spam our logs. However, it would be nice to have logging for edge cases, in particular if they result in _no path_ being returned at all. So maybe to start you could, instead of just logging any candidate exclusion right away, remember the last failure reason and only log it when it results in no path being returned.

Hey @tnull, thanks for the explanation, but I still find it hard to understand this issue. Please provide some material to understand the code.

**Comment by tnull** [comment]
> Hey @tnull, thanks for the explanation, but I still find it hard to understand this issue. Please provide some material to understand the code.

Mh, could you be a bit more specific on what you're having trouble understanding? Also, feel free to find me on LDK Discord and we can discuss this a bit more interactively.

**Comment by Lalitmohansharma1** [comment]
Yeah, I am finding it hard to understand code in `lightning/routing/router.rs `.
 and tnull#9465 is this your discord username?

**Comment by tnull** [comment]
> Yeah, I am finding it hard to understand code in `lightning/routing/router.rs `. and tnull#9465 is this your discord username?

Yep, feel free to reach out.

**Comment by Lalitmohansharma1** [comment]
> > Yeah, I am finding it hard to understand code in `lightning/routing/router.rs `. and tnull#9465 is this your discord username?
> 
> Yep, feel free to reach out.

Ok
