### ISSUE TITLE
Pad onion errors

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1723]
The spec recommends a fixed length to avoid giving away any fingerprinting on the error type. I believe we do not currently do this, but we should.

**Comment by freddiekrugerrand** [comment]
The spec [requires](https://github.com/lightning/bolts/blob/master/04-onion-routing.md#requirements-3) `pad_len = 256 - failure_len` (where `failure_len = 2 bytes failure_type + len(failure_data)`). IIUC this is already done [here](https://github.com/freddiekrugerrand/rust-lightning/blob/main/lightning/src/ln/onion_utils.rs#L365).
