### ISSUE TITLE
Inline `fail_holding_cell_htlcs` to avoid taking `channel_state` lock per-iteration to calculate the same thing

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1727]
To be done after we land #1656 See https://github.com/lightningdevkit/rust-lightning/pull/1656#discussion_r973569570

**Comment by ViktorTigerstrom** [comment]
I can of course take this one if we'd like :). Though maybe this is the perfect type of issue we'd like to leave for new contributors!
