### ISSUE TITLE
RGS `Update had same timestamp as last processed update` shouldn't be an error

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1746]
See https://github.com/lightningdevkit/rapid-gossip-sync-server/issues/17 but this just shouldn't be an error, we should probably try to apply anyway, though.

**Comment by G8XSU** [comment]
I will take this up, 
BOLT: "MUST set timestamp to be greater than that of any previous node_announcement it has previously created."
And we should re-broadcast if new timestamp in received msg is greater. 

Doubt: If we remove this check, we might apply and broadcast a few duplicate gossips. (non-rgs case)
is that fine?

Concern is when we receive same msg from multiple nodes.
