### ISSUE TITLE
Support providing a custom payment hash in the lightning-invoice invoice construction

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1803]

**Comment by ssbright** [comment]
Hello, I was unable to accomplish the previous PR I attempted but would like to try again. This seems like a good first issue for me so I will give it my best!

**Comment by dunxen** [comment]
> This seems like a good first issue for me so I will give it my best!

Let me know if you're looking for any pre-review :)

**Comment by ssbright** [comment]
Thanks! I will @dunxen

**Comment by ssbright** [comment]
@dunxen I could use a pre-review please! I wrote must of the code, but my test is failing and I am unsure why.
