### ISSUE TITLE
Add mutation testing

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#188]
We should start requiring full mutation coverage for functions as we build out our unit tests.
https://github.com/llogiq/mutagen looks like a good candidate, unless @apoelstra thinks we should use https://github.com/apoelstra/halfsleep.
Tagging 0.2 as our goal for 0.2 should be to move more towards better test coverage.

**Comment by apoelstra** [comment]
Nice!

halfsleep is unmaintained, and I'd probably start contributing to mutagen before I'd start maintaining it again.

**Comment by TheBlueMatt** [comment]
There’s a new option on the block though this one is language-agnostic and uses LLVM. No idea what the integration work would look like and it may end up just generating a ton of false positives for things in stdlib instead of our own code.

https://github.com/mull-project/mull

**Comment by dunxen** [comment]
So there's an even _newer_ option now called [cargo-mutants](https://github.com/sourcefrog/cargo-mutants) that doesn't require modifying any part of the source tree. It's just run as a cargo subcommand which is convenient. I'm running it on `main` now to see if we get anything useful. I'm already getting a few missed mutants which could indicate some gaps already found. :)

**Comment by apoelstra** [comment]
cc @tcharding if you're bored and want to play with this one, you might beat me to it:)

**Comment by tcharding** [comment]
Sweet, cheers. Do note before you put an policy in place I've found mutation testing enjoyable because one _really_ has to understand all the code tested but it is slow to implement in my experience.

**Comment by dunxen** [comment]
Mutating all functions over everything took about 12 hours (without `--jobs` for spawning multiple cargo processes) for me.
`2421 mutants tested in 777:57: 505 missed, 1122 caught, 778 unviable, 16 timeouts`
So I'm not sure what would be the best way to schedule something like this or maybe set it to run more granularly for PRs. One can filter by functions introduced in a PR. That might be more palatable for CI. Next would be figuring out the best way to [use the results](https://mutants.rs/using-results.html).

**Comment by tcharding** [comment]
I haven't played with `cargo mutate` yet but `mutagen` gives false positives is some cases, I don't think you'll be able to hard fail. An example I have been hitting often is `<` vs `<=`
```rust
fn abs(x: i32) -> u32 {
    if x < 0 { -x } else { x };
}
```

**Comment by dunxen** [comment]
> I haven't played with `cargo mutate` yet but `mutagen` gives false positives is some cases, I don't think you'll be able to hard fail. An example I have been hitting often is `<` vs `<=`
> 
> ```rust
> 
> fn abs(x: i32) -> u32 {
> 
>     if x < 0 { -x } else { x };
> 
> }
> 
> ```
> 
> 

Yeah, in this case then you'd need to add an ignore attribute to that function. So I think hard fail is still fine and the author can just explicitly ignore that function

**Comment by tcharding** [comment]
That is definitely one solution, I love to find one that didn't use ignore because I've found false positives pretty common but there is still some advantage in mutating. I'm super new to mutation testing but if you guys come up with anything can you cc me please. I did suggest on the `mutagen` repo adding an attribute like `rustfmt::skip`, it was favorably received but I wasn't able to implement it in the one try I had at it.

**Comment by tcharding** [comment]
Oh, thanks for the explanation - it is definitely not a total replacement for `mutagen` then. I ran it on rust-bitcoin yesterday but haven't gone through the output yet.

**Comment by dunxen** [comment]
> At that level of granularity I feel like showing a CI "X" is reasonable, even if we don't strictly require it for merging.

I think this would also be an important feature https://github.com/sourcefrog/cargo-mutants/issues/57, but I don't think it's a hard requirement to at least test it out. I'll play around some more and open a PR at some stage. Also seeing what I can contribute upstream.

**Comment by sourcefrog** [comment]
Hi, just thought I would let you know cargo-mutants can now do incremental tests on PRs, in https://mutants.rs/in-diff.html. Let me know over there if you have any feedback or hit any problems.

**Comment by dunxen** [comment]
> Hi, just thought I would let you know cargo-mutants can now do incremental tests on PRs

Hey! Thanks, that's awesome. I'll sure to give it a try soon and let you know how it goes 😄
