### ISSUE TITLE
Limit number of pending un-funded channel requests

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1889]
We need to limit the number of pending channel requests we have or we can OOM. We should probably just set some static limit of unfunded channels and close the oldest one when we get a request for a new one. Sadly I think this will likely allow for an attacker to prevent us from accepting new channels, but maybe that's okay.

**Comment by ariard** [comment]
See also the comments in dual-funding: https://github.com/lightning/bolts/pull/851#issuecomment-1326081967 We could prevent an attacker to censor our new channel acceptance by restraining new inbound connections. I don't think we have any default robust strategy yet, even you can a custom one before call to `new_inbound_connection`.

**Comment by ariard** [comment]
Yes -- Limiting the total number of inbound peers would be helpful both for dual-funding overflow and known per-peer overhead.
