### ISSUE TITLE
Provide local balance msat value in `ChannelForceClosed`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1898]
For accounting purposes, its nice to know what your local balance *was* when a channel was force-closed. This would allow you to see how many msat you lost to rounding.

**Comment by Cxxshyy** [comment]
if i could get some guidance i'd like to do this issue

**Comment by Cxxshyy** [comment]
@TheBlueMatt ok will have a shot but will ask a lot since i'm still new to rust

**Comment by Cxxshyy** [comment]
first question is what file handles the channel close event @TheBlueMatt

**Comment by tnull** [comment]
> first question is what file handles the channel close event @TheBlueMatt

You can find this event type in the documentation: https://docs.rs/lightning/latest/lightning/util/events/enum.Event.html#variant.ChannelClosed

**Comment by Lalitmohansharma1** [comment]
Hii,
I want to do this issue, and I am new to rust, so I will need some help.
I think this file handles channel close event : 
https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channel.rs 
Am i correct ?

**Comment by Lalitmohansharma1** [comment]
Sorry I think this file handles channel close event:
https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channelmanager.rs
@tnull Am  correct ?

**Comment by Cxxshyy** [comment]
ok thanks

**Comment by Cxxshyy** [comment]
what should the type be for last_local_balance_msat field @TheBlueMatt

**Comment by valentinewallace** [comment]
> what should the type be for last_local_balance_msat field @TheBlueMatt

Should be `u64`!

**Comment by Cxxshyy** [comment]
ok thanks

> > what should the type be for last_local_balance_msat field @TheBlueMatt
> 
> @Cxxshyy should be `u64`!

**Comment by Lalitmohansharma1** [comment]
Hey everyone, I'm new opensource, but there are some issues I don't understand and the ones I do are already assigned to someone.
i would like to to give a try on this issue ,so @Cxxshyy can i work with you? :)

**Comment by Cxxshyy** [comment]
@Lalitmohansharma1 hey man sorry i dont think this issue is big enough for 2 people to work on.

**Comment by Cxxshyy** [comment]
also 
![image](https://user-images.githubusercontent.com/74113508/210653469-f9afae39-d2ee-46b7-89b9-43144ad0cc73.png)
for this function here would i need to create a new function to obtain the local balance

**Comment by Lalitmohansharma1** [comment]
> @Lalitmohansharma1 hey man sorry i dont think this issue is big enough for 2 people to work on.

Ok :)

**Comment by valentinewallace** [comment]
> also ![image](https://user-images.githubusercontent.com/74113508/210653469-f9afae39-d2ee-46b7-89b9-43144ad0cc73.png) for this function here would i need to create a new function to obtain the local balance

Does this comment answer that: https://github.com/lightningdevkit/rust-lightning/issues/1898#issuecomment-1347474378 so just use `Channel::get_available_balances`?

**Comment by Cxxshyy** [comment]
```pub fn get_available_balances(&self) -> AvailableBalances``` this is the function signature where availableBalances is a struct however localBal is an u64 so how can i satisfy this when i call the function 
![image](https://user-images.githubusercontent.com/74113508/210892923-76776cdb-06a9-4911-831d-2db1da56a929.png)

**Comment by Cxxshyy** [comment]
ok i think i might have completed it now

**Comment by Cxxshyy** [comment]
nvm but close

**Comment by freddiekrugerrand** [comment]
@Cxxshyy / @Bolt-12 either of you actively working on this? Would be interested in picking it up if it's free.

**Comment by srikanth-iyengar** [comment]
Hey @TheBlueMatt I would like to work on this issue, is this up for grabs ?

**Comment by Mirebella** [comment]
Is this good to close, given that https://github.com/lightningdevkit/rust-lightning/pull/3235 was merged?
