### ISSUE TITLE
Move Payment Retrying into ChannelManager

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1932]
We've started down the path, now we need to land it (ideally all in one release so our API isn't randomly weird).

- [x] Address follow-up from #1916 
- [x] Deduplicate `PendingTLCsForwardable` events, see https://github.com/lightningdevkit/rust-lightning/pull/1916#discussion_r1070405522 
- [x] Support automatic retry methods for spontaneous payments
- [x] Move payment path scoring to `BackgroundProcessor` 
    - [x] Remove scoring methods from `Router` trait
- [x] Replace the `InvoicePayer` with invoice paying utility methods
- [x] Remove support for manual retries in `ChannelManager` + take `abandon_payment` private and call it on the user's behalf
- [x] Simplify `send_payment_with_retry` return value: don't include the `PartialFailure` variant, and instead generate `PaymentPathFailed` events for the failed paths on partial failure
- [x] Migrate `ScorerAccountingForInFlightHtlcs` tests from `InvoicePayer`: `considers_inflight_htlcs_between_retries` 
- [x] Remove `retry` field from `PaymentPathFailed`

**Comment by valentinewallace** [comment]
> Maybe #1969 should be tracked here too?

Good point! I can fix this building on #2014.
