### ISSUE TITLE
Stop haphazardly passing `InitFeatures` in message handlers

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1954]
`handle_{shutdown,open_channel,accept_channel}` etc methods all take an `InitFeatures` parameter because `ChannelManager` needed it and it was the cheapest way to pass them through. We could pass them through on every message handler, but there's little reason to since `ChannelManager` caches the last `InitFeatures` in the peer state anyway, and it would clean up the interface to just remove it.

**Comment by danielgranhao** [comment]
If no one has yet, I can try to tackle this.
