### ISSUE TITLE
Swap Gossip Message `PublicKey`s for `NodeId`s

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1973]
To improve the deserialization time of our network graph and address #960, we swapped the `PublicKey`s describing node ids directly in the graph with a new `NodeId` struct in #1107. This improved performance greatly, but missed that we're still deserializing `PublicKey`s a *ton* when reading a `NetworkGraph` - we store the original gossip messages in the graph itself with `PublicKey`s and have to do a bunch of key checking when reading the graph again.

Replacing the `PublicKey`s in gossip messages with `NodeId`s should give us yet again a huge speedup in the time it takes to read our network grpah.

**Comment by alecchendev** [comment]
I can try and pick this up! I see that the structs `UnsignedChannelAnnouncement` and `UnsignedNodeAnnouncement` use `PublicKey` and are embedded in `NetworkGraph`. Would this mainly involve changing these structs' `PublicKey` fields to `NodeId` and adapting the associated serialization?

**Comment by alecchendev** [comment]
Cool, I'll get started on this tomorrow.
