### ISSUE TITLE
Replace `OUR_MAX_HTLCS` constant with a config knob

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1990]
Basically what it says on the tin - add a new config knob and use it in place of `OUR_MAX_HTLCS`, writing an even TLV if its not 50 to break forwards compat.

**Comment by ariard** [comment]
The config knob should warn the post-anchor fee-bumping reserves should be scale in consequence (or we do that under the hood). And probably few other warnings.

**Comment by swilliamson5** [comment]
I'd like to help! I'll take this as a first issue. I'll need some guidance and I might also post in the Discord for help if needed.

**Comment by swilliamson5** [comment]
Sorry for the delay, working on trying to figure out how to properly test this. I'm relatively new to LDK and Lightning development so I could be in over my head here. Here's a code snippet for the "even TLV" change. Also, I added a new field to the `Channel` struct in `channel.rs` to replace the referenced constant where possible. Let me know if I am way off!

```
write_tlv_fields!(writer, {
...
  (27, self.channel_keys_id, required),
  (28, Some(self.max_accepted_htlcs), option),
});
```

**Comment by valentinewallace** [comment]
> Sorry for the delay, working on trying to figure out how to properly test this. I'm relatively new to LDK and Lightning development so I could be in over my head here. Here's a code snippet for the "even TLV" change. Also, I added a new field to the `Channel` struct in `channel.rs` to replace the referenced constant where possible. Let me know if I am way off!
> 
> ```
> write_tlv_fields!(writer, {
> ...
>   (27, self.channel_keys_id, required),
>   (28, Some(self.max_accepted_htlcs), option),
> });
> ```

You can write it as `required` and read it as an `option`, which is a bit more succinct, but what you have would work. Matt also mentioned in the top-level comment that it should only be written if it's not 50. 

But, this sounds like a fine start, feel free to open a draft PR and you can get feedback there :)
