### ISSUE TITLE
Allow Accepting HTLCs with less value than the onion claims to pay

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1999]
If so configured, an LSP may skim some funds off the top of an HTLC, but we really dont want them to mess with the onion. Thus, we need a way to override the amount the onion claims to pay so that we can accept an HTLC that has an onion that says it pays X, but only pays X-$(configured fee). I'm not exactly sure how best to let the user configure $(configured fee), but ignoring it entirely isn't super practical as we need some way to figure out if an MPP payment is complete or not.

TODOs:
- [x] Allow forwarding less than the amount in the onion v1 (#2319) 
- [x] Include the counterparty skimmed fee in `PaymentClaimed`
- [x] Link to https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/22 when it's merged

**Comment by valentinewallace** [comment]
cc https://github.com/lightning/blips/pull/25
