### ISSUE TITLE
 Refuse new updates after the ChannelMonitor has seen a funding spend confirmed

### ISSUE THREAD

**Issue by wpaulino** [lightningdevkit/rust-lightning#2013]
Requested as a follow-up in https://github.com/lightningdevkit/rust-lightning/pull/1922#issuecomment-1356842600.

**Comment by amit-62** [comment]
Hello @wpaulino I want to solve this issue. But I am new to this repo and need guidance to solve it.

**Comment by amit-62** [comment]
Thank you @TheBlueMatt

**Comment by amit-62** [comment]
Hello @TheBlueMatt I have created PR [#2038](https://github.com/lightningdevkit/rust-lightning/pull/2038) please review.
