### ISSUE TITLE
Store a cached `NodeId` for each of our Peers in `PeerManager`.

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2021]
See https://github.com/lightningdevkit/rust-lightning/pull/2016#discussion_r1099165609

**Comment by alecchendev** [comment]
I'm thinking the most intuitive way to do this might be to just add a field `Option<NodeId>` to `Peer` that gets stored whenever the `Peer`'s `their_node_id: Option<PublicKey>` gets set? Another way might be to keep a `HashMap<PublicKey, NodeId>` in `PeerManager`.
