### ISSUE TITLE
Wake background-processor on async monitor update completion

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2052]
Probably need some kinda future like we have for ChannelManager persistence. We should also improve the logging in monitor persistence.

**Comment by MaxFangX** [comment]
It would be great if this new future is broad enough that the 100ms sleeper future in the LDK background processor could be removed (or at least default to a much higher value, like once a minute). Even though we don't use LDK's background processor directly, it would be a strong signal to us that LDK has confidence in its provided mechanisms for waking the background processor when needed, and would thus give us the confidence to remove our process events timer downstream.
