### ISSUE TITLE
Expose a failure reason in `PaymentFailure`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2095]
When a payment fails completely, we should at least tell the user if its because the recipient rejected it or if we ran out of attempts.

**Comment by alecchendev** [comment]
I can pick this up! Would this mainly be a simple enum added to `Event::PaymentFailed` with some doc comments? In which case I can try and open a PR tomorrow

**Comment by alecchendev** [comment]
Oh okay all good then 👍

**Comment by rloomba** [comment]
hey @alecchendev! feel free to take this ticket

**Comment by alecchendev** [comment]
Sounds good @rloomba, thanks!
