### ISSUE TITLE
`rust-bitcoin` 0.30.0 upgrade may be annoying

### ISSUE THREAD

**Issue by tcharding** [lightningdevkit/rust-lightning#2121]
Hi,

We just released v0.30.0 of `rust-bitcoin`, assuming you guys are going to upgrade, can I ask a favour please. If the upgrade is painful can you please give me feedback. There is a fair bit of churn going on with crate smashing and I'd like to make it as painless as possible for downstream. I don't personally work on any code that uses `rust-bitcoin` so I have a tendency to get tunnel vision.

If its super painful, just prod me and I can lend a hand.

Thanks

**Comment by Kixunil** [comment]
FYI I did it for multiple project and it was fine. Took a bit of time but nothing serious.

**Comment by tcharding** [comment]
Oh cool, thanks @Kixunil - well this issue can be closed then, excuse the noise.
