### ISSUE TITLE
CI Test for unknown cfg assertions

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2184]
Rust doesnt check that the cfg assertions we use are actually correct, and it would be fairly easy for a typo to slip in. We should have some kind of CI test which greps the code for all cfg checks, then compares the conditions against the known set of conditions (debug_assertions, anchors, test, etc) plus combinators (any, all, not, etc).

**Comment by henghonglee** [comment]
Hi @TheBlueMatt i'd like to have a go on this one. a couple of questions off the top of my head
1/ is there a prefered tool for grep?
2/ where should this test be located in the code?

**Comment by rjtch** [comment]
Hi, can i take this task?
