### ISSUE TITLE
Sample Node Signatures dont seem to work on websites now

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2188]
They seemed to use to work great any time I tried them, but now when I try them it either fails or seems to recover a different pubkey than mine (which is indistinguishable from an invalid signature). I don't see anything that changed in our code so maybe something changed elsewhere or we're buggy for some messages?

**Comment by dunxen** [comment]
BOLT 11 signature recovery? Not sure I follow.

**Comment by dunxen** [comment]
> No, like the zbase32 signmessage stuff

Didn't know the sample had that. Probably just missed it. I'm playing with it at the moment for V2 establishment stuff. Might take a peek.
