### ISSUE TITLE
Pass scoring params through the router

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2189]
Currently we require a "stateless" scorer, one which returns an absolute score with no context besides the channel and liquidity. This is somewhat annoying, though, for folks who want to have different scorers at different times - they'll have to create two separate scorers and pass them in. You can see this in the API for ProbabilisticScorer, which requires you pass the params at construction-time. Instead, we should parametrize the scorer with an associated "parameter" type, which is then passed to the router function itself, and allows passing a different, eg, ProbabilisticScorerParams per route-finding call.

Should be pretty straightforward to do - just add a assicated type to the `Score` trait, then add that as an argument to the score-fetching method and make it an argument to the get_/find_ route function.

**Comment by henghonglee** [comment]
Hi @TheBlueMatt i'd like to give this one a try

**Comment by henghonglee** [comment]
I did some reading of the code and have some questions about this task. 

From how I understand the scorer system, for each time a get_route / find_route is called, you need to use a scorer. a scorer is currently a single-use object that holds a bunch of states.
The various implementations of `Score` are these single-use objects that encode the "what" (what the parameters are) and also the "how" (how the scoring is calculated)

These include:
`FixedPenaltyScorer`
`ProbabilisticScorer`
`ScorerAccountingForInFlightHtlcs`
`BadChannelScorer`
`BadNodeScorer`

it seems that `find_route` requires one of these scorers and is a central public function that does everything to find a single route from a payer to a payee. 

IMHO, I think these scorer constructs actually do a nice job of abstracting the logic and accompanying state required for that logic 

maybe I did not understand "somewhat annoying, though.. different scorers at different times" right in the original text, did you mean to score each channel differently in a single `get_route` fn call? I can see that it might be very tricky to compose different scorers for a single get_route.
Maybe the complexity also lies in the multi-path payments and how each found route affects the next and requires a different scorer?

Could you further elaborate on where the annoyances lie in trying to achieve get_route/find_route with multiple scorers? is it memory related? speed/performance related? or mainly in the ergonomics of the implementations?

**Comment by henghonglee** [comment]
![image](https://user-images.githubusercontent.com/906931/233031504-89ba7243-dbc9-4f8f-8be6-5b0fb1a25536.png)
![image](https://user-images.githubusercontent.com/906931/233031886-5d23dfc6-e63e-4151-ac00-1cebb1b3441e.png)

@TheBlueMatt 
did you mean something like this?

**Comment by henghonglee** [comment]
Hi, @TheBlueMatt
I do have an unfinished draft that I would like to have you take a look at. It seems I would be making a large number of changes so I just wanted to make sure (once again) that I'm still on the right track with regard to the task. 

Created a draft PR here https://github.com/lightningdevkit/rust-lightning/pull/2237/files.
