### ISSUE TITLE
Make lockablescore RW

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2192]
Currently `LockableScore` only has one `lock` and then returns a `Score` that has some mutable methods and some non-mut methods. We really should make `LockableScore` have both a read and write lock which would make parallel route-finding trivial, rather than somewhat convoluted today.

**Comment by jbesraa** [comment]
I created an initial pr for this https://github.com/lightningdevkit/rust-lightning/pull/2197
