### ISSUE TITLE
Explicitly reject routes which double back

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2215]
I managed to generate a route which went out over an SCID and came right back over the same SCID, which nodes rejected, but really should have been rejected by LDK prior to sending over it.

We might also consider rejecting such forwards (I think we allow them?) but there's not a ton of reason to.

**Comment by Sharmalm** [comment]
Hey can i try this issue? 
I believe we have to add check pre-send in `router:: get_route` .
