### ISSUE TITLE
Fail to apply gossip update for invalid chain hash 

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2228]
Currently, [`NetworkGraph::update_channel_unsigned`](https://docs.rs/lightning/latest/lightning/routing/gossip/struct.NetworkGraph.html#method.update_channel_unsigned) and similar methods will happily apply updates, even if they don't match its `genesis_hash`. This for example happens when syncing a testnet graph with the mainnet RGS url. 

However, we should check the given chain hash in `NetworkGraph::update_channel_intern` and refuse to apply any updates that don't match the network we're on.

**Comment by freddiekrugerrand** [comment]
I'd like to pick this up if it's available!
