### ISSUE TITLE
Replace intermediate Vecs with iterators

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2240]
After  #2044 we have a bunch of things building intermediate vecs that could be iterators (or return `impl Iterator`), we should do that. Should be a fun puzzle for anyone who wants to play with more tricky rust changes and the test coverage is pretty good so it should be easy to do without going through rounds of feedback.

**Comment by upjohnc** [comment]
I'll work this ticket

**Comment by upjohnc** [comment]
PR: [#2290](https://github.com/lightningdevkit/rust-lightning/pull/2290)
