### ISSUE TITLE
Move `PeerManager` `ErrorMessage` logging to `UnsafeString`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2291]
We currently just print "with non-ASCII error message" to log when we see non-ASCII chars, but should instead use our fancy `UnsafeString` wrapper to display the unsafe string and ignore control chars.

**Comment by vladimirfomene** [comment]
Hello @TheBlueMatt! I'm working on a fix for this issue. When you say `UnsafeString` are you referring to this code pattern: `unsafe { std::slice::from_raw_parts(data, datalen)`

**Comment by valentinewallace** [comment]
FYI it's called `UntrustedString`, not `Unsafe`
