### ISSUE TITLE
Add channel id/peer id to Logger's `Record`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2292]
We should have explicit spots in the log Record struct for peer id and channel id (both id and user_id, I think) and fill them in as needed. Would make the logs much more structured and ensure we dont forget to include them.

**Comment by henghonglee** [comment]
Hi, @TheBlueMatt I can work on this task.

**Comment by henghonglee** [comment]
do have a couple of quick questions/confirmations here for 
peer_id are we looking to do the `u8` one? which sounds like it's the index of the current peer list 0-255 (CMIIW)
channel_id is the channel id `[u8;32]` and not the scid(short channel id)

**Comment by henghonglee** [comment]
Hi @TheBlueMatt, this one is ready to be reviewed
