### ISSUE TITLE
Don't panic when fallen behind

### ISSUE THREAD

**Issue by TonyGiorgio** [lightningdevkit/rust-lightning#2325]
This panic has some suggestions in it but makes it impossible to do anything about it by panicing. It should probably either handle what it is recommending in the logs or it logs and disconnects peer at the very least so that a user can actually force close like it is suggesting.

https://github.com/lightningdevkit/rust-lightning/blob/4dce209e972a7aeb18d99122ca293e6a272844b1/lightning/src/ln/channel.rs#L4112-L4120

**Comment by TonyGiorgio** [comment]
I had the other peer close the channel and it's been over 100 blocks and the funds are on chain. However, I'm still getting this issue. It's quite clear that panicing is a terrible way to handle this as it makes the entire node inoperable.

**Comment by TonyGiorgio** [comment]
> this may not be practical for certain application deployments

I'm not sure if it would be practical for any application deployments. When an LDK node launches, it should be expected that it should reconnect to the peers it has a channel with, by default. A user manually going into settings or making an API call for each channel partner is not something I think anyone would suggest.

So with auto connection behavior being the norm, and prioritizing *quick* auto connections in order to not slow down the user (especially mobile app users), I don't really see an opportunity to take any action. I have even tried to be as quick as possible to go into settings and disconnect peer before it attempted to connect. Sadly, we all created software that is too quick. 

I cant think of any way to provide a good user experience around quick reconnections and working around this bug. Unfortunately, without `async` traits on state changes, we're a little more proned to data inconsistencies than we would like to be. So being able to work around force closures like this is a necessity. Hard to do when it crashes.

**Comment by TonyGiorgio** [comment]
Needless to say that's pretty extreme to expect users to both understand what happened and work around it.

**Comment by TonyGiorgio** [comment]
> Maybe? I think the theory with a panic here is that it gives developers a chance to fix they go to production, as its really something we shouldn't ever hit, ever.

I'm sure even in rare disk failure events, LND has probably even had it's fair share of out of sync state updates, esp on raspberry pi's. 

> lack of async persistence shouldn't result in inconsistency, only more difficult application programming - can you describe in a bit more detail how this corruption happened and why it can't be fixed?

We can't call any blocking code, so it makes ensuring persistence through sync calls difficult when indexeddb is async. We essentially have to `[spawn_local](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html)` to send it to the background to write while we immediately return. So state persisting issues can occur.

I might be able to use [crossbeam channels](https://docs.rs/crossbeam/latest/crossbeam/channel/index.html) inside the `sync` function so try that. Otherwise we will have to write to local storage since that works with `sync` and then check that instead.

**Comment by TonyGiorgio** [comment]
I think we've been able to work around some of this by saving to localstorage with a sync call and always reading from that first, though localstorage is not the recommended way to save data in browsers but we need `async` to always save to indexeddb instead.

I still don't think panicing here is the best approach. It's cripling the ability for the wallet dev to provide any support at all to users this happens to. What is going to happen when state is saved remotely and the remote server missing an update but it pulls it down one state behind and panics? I assume VSS wants to be capable of saving remote state and there's no 100% guarentees around that always working. 

Users are expected to somehow take the data, go into some external application to "do something" and recover their funds? All because a panic happened instead of a disconnection? It doesn't make any sense to me why that's the recommended option. By panicing, it's impossible to even open the app to be able to tell what is going on.

**Comment by TheBlueMatt** [comment]
The current approach is to have a separate "recovery" tool which accepts a set of `ChannelMonitor`s and uses peer storage (see #2943 and the break-out PRs) to claim what we can.
