### ISSUE TITLE
Dont force-close on dust exposure if remote reserve is more than dust

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2336]
Just fail the HTLC, force-closing is dumb since we can fail the HTLC ~immediately.

**Comment by ariard** [comment]
Yes this sounds correct to me if the dust HTLC does not materialize on neither the holder or the counterparty commitment transaction.

**Comment by benthecarman** [comment]
Was looking into this one but seems like an error message is correctly sent for any dust exposure concerns

https://github.com/lightningdevkit/rust-lightning/blob/57911dcd415d2f9cafdbcef1ab9b0d38de3954fa/lightning/src/ln/channel.rs#L4165
