### ISSUE TITLE
Claim HTLCs even if we're over our dust exposure if counterparty has reserve

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2352]
If we're close to our dust exposure limit and receive an HTLC which would put us over, we will fail that HTLC back, but there's no need to, if the counterparty has reserve greater than the dust exposure we should consider that sufficient.

**Comment by ariard** [comment]
Even if the counterparty’s reserve is more than our current holder dust exposure, we’re still exposed if the counterparty confirms a transaction where the dust outputs are committed as fees.
