### ISSUE TITLE
Parse bolt11 error

### ISSUE THREAD

**Issue by arronzhang** [lightningdevkit/rust-lightning#2445]
When i test parse bolt11 in regtest network, the `payee` lost.

Example:

Online:

https://lightningdecoder.com/lnbcrt100n1pjthklwpp5fyw8vc9q2fu2rv2rxzy027jnmpm4mrgj0xwtrnxsk9208clg664qdqqcqzzsxqyz5vqsp5yu90phyrcn5vy60dltxtjukzqvcs3zgtzlucvxezjhwdaqt5xwgq9qyyssqeme2dv5kt6wxeqvgyl57hwzkr4rxn0pmlvxqfkxpwmvxhzhvma2n6nr06emj033r5k3xfd8phm46mlkdy0rrrqxpzm64qanhy3awyycpw4rz5g

Payee Pub Key
02b6620f6c560f372d9ea229eb9bc65a60168a490e9805d4ee23ca2e5b3ff7d25b

lightning-invoice = "0.24.0" `bolt11.parse::<Bolt11Invoice>()` lost the `PayeePubKey`.

Bolt11Invoice { signed_invoice: SignedRawBolt11Invoice { raw_invoice: RawBolt11Invoice { hrp: RawHrp { currency: Regtest, raw_amount: Some(100), si_prefix: Some(Nano) }, data: RawDataPart { timestamp: PositiveTimestamp(1690033134s), tagged_fields: [KnownSemantics(PaymentHash(Sha256(491c7660a05278a1b1433088f57a53d8775d8d12799cb1ccd0b154f3e3e8d6aa))), KnownSemantics(Description(Description(""))), KnownSemantics(MinFinalCltvExpiryDelta(MinFinalCltvExpiryDelta(80))), KnownSemantics(ExpiryTime(ExpiryTime(86400s))), KnownSemantics(PaymentSecret(PaymentSecret([39, 10, 240, 220, 131, 196, 232, 194, 105, 237, 250, 204, 185, 114, 194, 3, 49, 8, 137, 11, 23, 249, 134, 27, 34, 149, 220, 222, 129, 116, 51, 144]))), KnownSemantics(Features([0, 66, 2]))] } }, hash: [80, 180, 2, 249, 181, 28, 134, 250, 230, 49, 185, 17, 1, 54, 253, 89, 239, 101, 12, 68, 84, 67, 220, 36, 100, 7, 211, 81, 158, 144, 224, 163], signature: Bolt11InvoiceSignature(RecoverableSignature(cef2a6b2965e9c6c818827e9ebb8561d4669bc3bfb0c04d8c176d86b8aecdf553d4c6fd67727c623a5a264b4e1beebadfecd23c63180c116f5507677247ae21301)) } }

**Comment by valentinewallace** [comment]
Have you tried this? https://docs.rs/lightning-invoice/latest/lightning_invoice/struct.Bolt11Invoice.html#method.recover_payee_pub_key

**Comment by arronzhang** [comment]
@valentinewallace Thanks, it works.
