### ISSUE TITLE
Make `Error handling message from.*; ignoring: Couldn't find channel for update` logs less scary

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2471]
People keep seeing that message and asking if its an indication of an issue. It almost never is, so the log needs to be less scary.

**Comment by AnmolSirola** [comment]
@TheBlueMatt Can I work on this issue.

**Comment by valentinewallace** [comment]
> @TheBlueMatt Can I work on this issue.

Go for it @AnmolSirola
