### ISSUE TITLE
`impl ToSocketAddrs` for `Hostname` (and possibly other `NetAddress` variants)

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2535]
In #2134 we added the `FromStr` trait implementation to `NetAddress`.

As a follow-up it would be nice to also add a `ToSocketAddrs` implementation to allow easy resolution for our `NetAdresses`, which would be useful for the `Hostname` variant in particular.

This would also allow us to get rid of the `NetAddress` newtype in LDK Node, which currently makes use of `ToSocketAddrs` (cf. https://github.com/lightningdevkit/ldk-node/blob/a9bb2e9c5b9892213b244bc2fb474a5fe0c76802/src/types.rs#L360-L385).

**Comment by slanesuke** [comment]
I'll take this one as my first issue if that works?
