### ISSUE TITLE
Check best block before connecting a new one in `ChainMonitor`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2538]
Similar to #987, but I suspect made much worse by #2528 - if we get a `ChannelMonitor` from the `ChannelManager` it may (or may not) have the same best-block as the rest of the monitors in `ChainMonitor`. Thus, we need to handle it somehow and make sure things get to the same state when adding a new monitor. I think the easiest way to do this for now is to say that `ChainMonitor` has to get block connection events *after* `ChannelManager`, and check best block before connecting in the `ChainMonitor` loop.

Tagging 117 as I'm afraid this may be much more likely and we should avoid regressing here.

**Comment by jbesraa** [comment]
@TheBlueMatt when is .117 scheduled to be released?
