### ISSUE TITLE
for 117 release notes, remember pending changelog pr number is off

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2565]
https://github.com/lightningdevkit/rust-lightning/pull/2549#discussion_r1320293966

**Comment by ariard** [comment]
@TheBlueMatt what is wished 0.0.117 timeline already as of today ? seeing a bunch of 0.0.117 tagged PR / issues.

we could have a release schedule issue like core one: https://github.com/bitcoin/bitcoin/issues/27758 to have more visibility. right now looking on latest releases (from 0.0.116 to 0.0.112) can’t say we had a clear inter-release interval.
