### ISSUE TITLE
Improve (pre-flight) probing test coverage

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2585]
In https://github.com/lightningdevkit/rust-lightning/pull/2534 we introduced pre-flight probing and a corresponding test case.

However, as noted in https://github.com/lightningdevkit/rust-lightning/pull/2534#discussion_r1323420867, the test case currently relies on checking the logs, which can be improved upon.

As a follow-up, we should DRY up the MPP-probing test logic, add more tests on this basis. In particular we should test the following things independently: a) all MPP probes are executed b) some are excecuted, some are avoided due to liquidity constraints c) we avoid probing for possibly announced last hops.

**Comment by alexanderwiederin** [comment]
Happy to look into this if this is available!
