### ISSUE TITLE
[Persistence] Don't persist ALL channel_monitors on every bitcoin block connection. 

### ISSUE THREAD

**Issue by G8XSU** [lightningdevkit/rust-lightning#2647]
Currently on every bitcoin block update we persist all channel_monitors with updated best_block. 

This can be troublesome for large node operators with 1000's of channels. 

It also causes a thunder herd problem ([ref](https://en.wikipedia.org/wiki/Thundering_herd_problem)), and hammers the storage with many requests all at once.
  
Ideal outcome: After doing this, Ldk's IO footprint should be reduced by ~50 times and processing time to sync each block will be drastically reduced(this can be very long for nodes with 1000s of channels).

**Comment by benthecarman** [comment]
Probably easiest way to do this would just have a config option and do the writes in batches
