### ISSUE TITLE
Stop reading monitors when persisting in updating persister

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2706]
Turns out this line is brutalizing our heap and leading to fragmentation, it needs to go away - https://github.com/lightningdevkit/rust-lightning/blob/281a0aead744351c43fce660cf78f955fc969bfb/lightning/src/util/persist.rs#L613

**Comment by domZippilli** [comment]
cc: @G8XSU 

I decided to try this out real quick, and it passes unit tests in the file. I wouldn't do it exactly like this (probably would at least get the TLV macro to work) but I would imagine this allocates very little beyond the monitor read's `Vec<u8>`? 

https://github.com/lightningdevkit/rust-lightning/commit/8f71e3a21f89947bed7a375622518ce952bc2487

**Comment by domZippilli** [comment]
Yeah, when we had the discussions on the RFC I think there was a general preference to avoid duplicate state in the MUP, which is how we ended up reading it from storage like this. It'd be ideal, I suppose, to read just the required bytes, but ranged reads in KVStore seems like asking a lot.
