### ISSUE TITLE
Expose channel features/type in ChannelDetails

### ISSUE THREAD

**Issue by wpaulino** [lightningdevkit/rust-lightning#2710]

**Comment by vladimirfomene** [comment]
Hi @wpaulino ! Can I take this up

**Comment by valentinewallace** [comment]
> Hi @wpaulino ! Can I take this up

Go for it @vladimirfomene!

**Comment by vladimirfomene** [comment]
@wpaulino quick clarification are you referring to exposing `ChannelFeatures` in `ChannelDetails`?

**Comment by vladimirfomene** [comment]
is it not already exposed here: https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channelmanager.rs#L1534
