### ISSUE TITLE
Make on-close `channel_update` messages more robust

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2711]
When we force-close a channel we send an advisory `channel_update` to the currently connected peers to let the world know that the channel is now closed (by setting the disable bit). This doesn't do anything if we force-close on startup, because we have no peers. We should retry broadcasting these at some point in the future by caching them a bit. Other nodes currently dont do this (and absolutely should), but for now we should at least make our more reliable.

**Comment by shaavan** [comment]
Can I give this a try?

**Comment by shaavan** [comment]
I've tried expanding upon a different approach!

I've been monitoring our node's ability to reach out to anyone when it's time to broadcast, whether that happens at startup or any other timer while the node is running.

If, for some reason, we miss the broadcast, we'll just give it another go and resend the pending broadcast messages.

**Comment by shaavan** [comment]
@TheBlueMatt 
A gentle ping! :)

The PR resolving this issue (#2731) is ready for review.
