### ISSUE TITLE
Differentiate between coop close and force-close in `Balance`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2738]
There is no way to tell whether a `Balance` is for a coop close or an HTLC or a force-close. We should expose that info.

**Comment by moneyball** [comment]
119 worthy?

**Comment by Jasonvdb** [comment]
Would be interested in using this in Bitkit

**Comment by dunxen** [comment]
I can pick this up tomorrow. I'm not sure it would get in by 124 with some of the other work in progress but will make an attempt 👍
