### ISSUE TITLE
Bump `rust-bitcoin` to version 0.31

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2745]
After we upgraded to `rust-bitcoin` 0.30 in #2740, we should look into upgrading to 0.31.0 soon to keep up with the most-recent version. However, this time we should try to coordinate the upgrade with the wider ecosystem, especially BDK (cc @notmandatory), which just recently was unblocked from upgrading as `rust-miniscript` released the upgraded version 11.0 (see https://github.com/bitcoindevkit/bdk/issues/1196).

I think we should release 0.0.119 with `rust-bitcoin` 0.30 and then look to upgrade to 0.31 for the following release.

**Comment by notmandatory** [comment]
Related PR for BDK is bitcoindevkit/bdk#1177 since we also depend on rust-miniscript being updated I'm not 100% sure this will make it into our 1.0 release milestone.

**Comment by jirijakes** [comment]
Hi all!

It seems nobody is actively working on rust-bitcoin upgrade yet? If it's so, I would like to start working on upgrading to rust-bitcoin 0.32, with the goal of starting to open draft PRs within a few days.

I am aware of https://github.com/bitcoindevkit/bdk/issues/1422 and the linked Discord discussion. I don't know whether there have been some other discussions on this topic.

**Comment by jirijakes** [comment]
> It would be great if we could do the upgrades individually though, i.e., fist open a PR for 0.31 and then another one 0.32.

Alright, no problem with this.
