### ISSUE TITLE
Log the errors before we return them from `ChannelManager::do_accept_inbound_channel`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2754]
In general, our users often don't log the specific error strings from things like `APIError` (why would they, its not generally human readable nor machine-actionable), so we're left kinda in the dark when debugging. We should really make sure we duplicate the error to logs before we return, ensuring all errors are in one place where we can see them.

**Comment by Jossec101** [comment]
Hey @TheBlueMatt, I took a first iteration of this in #2807, looking forward for comments!
