### ISSUE TITLE
Add `PaymentHash` to log `Record`s

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2767]
Users often want to track a single HTLC across multiple channels and through the entire pipeline, which should be doable with the new logging metadata wrappers.

**Comment by nafisalawalidris** [comment]
Hello @TheBlueMatt, I'm interested in working on this issue and adding PaymentHash to log records. I believe this enhancement will be valuable for users tracking HTLCs across multiple channels and through the entire pipeline.

**Comment by jbesraa** [comment]
hey @nafisalawalidris 
are you still interested in doing this?
