### ISSUE TITLE
`Channel::get_dust_buffer_feerate` comment doesn't match code

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2815]
I think the code should be changed. Pointed out at https://github.com/lightningdevkit/rust-lightning/pull/2808#discussion_r1441702317

**Comment by jbesraa** [comment]
I would like to work on this issue as part of the next Review Club. I will run it on Tuesday (March 26th), and by the end of the session I believe there will be an open PR.
