### ISSUE TITLE
Allow for user-specified error message to `force_close_with*_broadcasting_txn`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2840]
We have to send an error message to peers, so we might as well let the user configure it.

**Comment by Sharmalm** [comment]
Hey @TheBlueMatt can i try this issue?

**Comment by Sharmalm** [comment]
Ok, 
So in this issue, we have to allow users to send error message while `force_close_with*_broadcasting_txn` and `force_close_without_broadcasting_txn` both, right?

**Comment by Sharmalm** [comment]
I have made Pr for this issue, please review[](https://github.com/lightningdevkit/rust-lightning/pull/2889)
