### ISSUE TITLE
Expose method to send node announcement to specfic peer

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2866]
Currently we only expose a general `PeerManager::broadcast_node_announcement` method that allows to broadcast to all connected peers.

We should also expose a corresponding method for a specific peer, which would allow us to trigger it after channel opening.

**Comment by ikeogu** [comment]
Good morning dear @tnull, I want to contribute to this, please can you provide me with more details while I get the design document ready?

**Comment by VanshulB** [comment]
Hey, I would like to work on this issue, is this up for grabs?
