### ISSUE TITLE
`<Future as std::..::Future>::poll()` always allocates, growing until we're woken

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2874]
`<Future as std::..::Future>::poll()`, if `state.complete` is not set, always pushes the provided waker onto the `callbacks` vec. This means if we get `poll`'d regularly our memory will grow and grow until we get woken, which may be quite a while. Thus, this may end up using a very nontrivial amount of memory, at least on busy nodes.

**Comment by nate-lightspark** [comment]
To add more color to the issue, carrying notes from the Discord thread:

Looking at the memory profiler run with dhat leads to the result in the screenshot. The hot piece looks to be chain_monitor.get_update_future() :

[Profiler Result 1](https://drive.google.com/file/d/1o_RJJMJ_cRm9QVbu9novJn86LZAwYOmd/view?usp=sharing)

[Profiler After Change]
(https://drive.google.com/file/d/1lvL9VMZX4plZlxxmt2IZP6JCCGDMsnJB/view?usp=sharing)

It is an adapted from [this example code](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning-background-processor/src/lib.rs#L704)

The code block is like this for the severe memory leak: [Gist 1](https://gist.github.com/nate-lightspark/8828bc4e11fdfa8d077b5b4f00badc29)

Change is like this, seems to be resolving the issue (or makes it less severe): [Gist 2](https://gist.github.com/nate-lightspark/9feacceaafc4ce157d757877a1f15595)
