### ISSUE TITLE
Rename `payment_parameters_from_zero_amount_invoice` to imply amount-less, not 0-amount

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2879]
`lightning-invoice` treats missing amount differently from set amounts, but the whole zero-amount thing is about...zero amounts. Do we actually support zero amounts properly or only invoices with no amount (which presumably other lightning nodes can't create)? Should we be refusing to deserialize invoices with no amount at all?

**Comment by jkczyz** [comment]
Hmm... do you have more background on this issue? I always thought "zero-amount" was synonymous with "amount-less" but that the latter was the accurate term.

**Comment by jkczyz** [comment]
Here are old issues from other implementations for amount-less invoices:
- https://github.com/ElementsProject/lightning/issues/534
- https://github.com/lightningnetwork/lnd/issues/564
- https://github.com/ACINQ/eclair/issues/1478#issuecomment-652851241

**Comment by srikanth-iyengar** [comment]
I would like to work on this issue, is this up for grabs ?

**Comment by mubarak23** [comment]
@TheBlueMatt can i work on this
