### ISSUE TITLE
Consider allowing for BOLT12 payments over unannounced channels

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2952]
Currently, we only allow for BOLT12 payments if the introduction point is an announced node both payer and payee are connected to. It is my understanding that this is at least partially intentional to discourage leaking the payer's IP to the payee.

However, this makes for an unexpected UX where users could send payments via an intermediate node, but not via a directly-connected private channel. 

It would be nice if we could reconsider if we could relax some of the checks along the lines of https://github.com/tnull/rust-lightning/commit/8138bec3954e85da3e1b1b8b9593c5f9528e424d, or, at least allow the user to opt into private-channel BOLT12 payments via a config option.

**Comment by jkczyz** [comment]
> Once we can build multiple paths, we can maybe detect this situation (node with only private channels and no known-public peers) and include both a one hop and two hop hint.

Question is which peer if we have more than one? Presumably, in this situation we are paying a peer, so we aren't revealing anything to the peer by using a one-hop path. But with a two-hop path we are potentially revealing another peer.

> This might end up actually mattering beyond test suites, too, as we'll end up in the same situation (as far as we know) if we're running without a network graph at all. I kinda wonder if we shouldn't just always pick a peer and announce with that as an intro node if we're private and we don't think we have a network graph (or its really small).

Is this essentially the case where our only peers are LSPs? Maybe we consider all peers when we are unannounced, still preferring those with more channels. Then if we have an empty `NetworkGraph`, those peers still can be chosen. 

```diff
diff --git a/lightning/src/blinded_path/message.rs b/lightning/src/blinded_path/message.rs
index 1f3f5a1fa..369a12243 100644
--- a/lightning/src/blinded_path/message.rs
+++ b/lightning/src/blinded_path/message.rs
@@ -28,11 +28,11 @@ use crate::util::ser::{FixedLengthReader, LengthReadableArgs, Writeable, Writer}
 
 use core::mem;
 use core::ops::Deref;
 
 /// An intermediate node, and possibly a short channel id leading to the next node.
-#[derive(Clone, Debug, Hash, PartialEq, Eq)]
+#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
 pub struct ForwardNode {
        /// This node's pubkey.
        pub node_id: PublicKey,
        /// The channel between `node_id` and the next hop. If set, the constructed [`BlindedHop`]'s
        /// `encrypted_payload` will use this instead of the next [`ForwardNode::node_id`] for a more
diff --git a/lightning/src/onion_message/messenger.rs b/lightning/src/onion_message/messenger.rs
index ee49d00e9..702757242 100644
--- a/lightning/src/onion_message/messenger.rs
+++ b/lightning/src/onion_message/messenger.rs
@@ -502,12 +502,13 @@ where
                let mut peer_info = peers
                        // Limit to peers with announced channels
                        .filter_map(|peer|
                                network_graph
                                        .node(&NodeId::from_pubkey(&peer.node_id))
-                                       .filter(|info| info.channels.len() >= MIN_PEER_CHANNELS)
+                                       .filter(|info| !is_recipient_announced || info.channels.len() >= MIN_PEER_CHANNELS)
                                        .map(|info| (peer, info.is_tor_only(), info.channels.len()))
+                                       .or_else(|| (!is_recipient_announced).then(|| (peer, false, 0)))
                        )
                        // Exclude Tor-only nodes when the recipient is announced.
                        .filter(|(_, is_tor_only, _)| !(*is_tor_only && is_recipient_announced))
                        .collect::<Vec<_>>();
```

**Comment by jkczyz** [comment]
Ah, sorry I meant "we're getting paid by a peer". Including a one-hop path leaks that payee's node id, which the payer already has. So they learn they are paying their own peer (if they didn't already know that). With both a one-hop and a two-hop path, the payee is leaking that and potentially another peer unless they happen to choose the payer from their set of peers.

**Comment by jkczyz** [comment]
Another issue that we'll need to solve is paying through a `BlindedPath` where we are the introduction node. For onion messages, we'll advance the path by one:

https://github.com/lightningdevkit/rust-lightning/blob/b8cdde8af64189fd1567cbc85cfae26c610af969/lightning/src/onion_message/messenger.rs#L850-L853

But for payment paths, we don't yet have the equivalent.

https://github.com/lightningdevkit/rust-lightning/blob/b8cdde8af64189fd1567cbc85cfae26c610af969/lightning/src/routing/router.rs#L1936-L1937

Ran across this when trying to write a test for the two unannounced nodes case.
