### ISSUE TITLE
Rework/increase scoring params

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3040]
I think we were a little too conservative on our scoring params and we end up too strongly preferring to avoid fees, when most lightning users actually expect to pay some fees for reliable payments. We should probably at least double our fee params.

**Comment by benthecarman** [comment]
FWIW we need to increase them much more than 2x and still have some reliability issues

https://github.com/MutinyWallet/mutiny-node/blob/68d545d1f82ba0d0e64980d056dc16ee7f00d457/mutiny-core/src/node.rs#L1943
