### ISSUE TITLE
`OffersMessageHandler` impl for `ChannelManager` accesses time

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3097]
We have users who can't access time due to being in WASM, and while we'd like to move them to no-std, we can't do that until we get to rust-bitcoin 0.32. Thus, for our next release, we either need to upgrade to rust-bitcoin 0.32 or we need to drop the time accesses in the `OffersMessageHandler` impl.

**Comment by jkczyz** [comment]
Note that `timer_tick_occurred` is also affected for removing stale payments (i.e., stuck `AwaitingInvoice`).

https://github.com/lightningdevkit/rust-lightning/blob/2701bc512ad0d73a3309bf87a6b2487b2bfe00bf/lightning/src/ln/channelmanager.rs#L5711-L5722
