### ISSUE TITLE
Upgrade to `rust-bitcoin` 0.32

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#3100]
In #3063 we bumped to `rust-bitcoin` 0.31.

Synced with BDK and they will make the move to 0.32 in the next release (https://github.com/bitcoindevkit/bdk/issues/1422), which means we're not only free to upgrade but also should do so ASAP.

**Comment by jirijakes** [comment]
> @jirijakes Are you already working on this or did you intend to soon? Otherwise I'm happy to pick this up next week.

I have not started yet and I don't think I would get to it before second half of June. So, please feel free to start.
