### ISSUE TITLE
Expose `advance_path_by_one`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3134]
In #3132 we created `advance_path_by_one` to handle the case where are the intro node on a payment, but I believe LNDK may need that as well. We should check with them and then maybe expose it.

**Comment by orbitalturtle** [comment]
@TheBlueMatt Yes confirmed this would be helpful!

**Comment by valentinewallace** [comment]
@orbitalturtle Do you need to be able to advance blinded *message* paths as well, or just payment paths?

**Comment by orbitalturtle** [comment]
@valentinewallace Ah yup we need it for messages as well

**Comment by valentinewallace** [comment]
> @valentinewallace Ah yup we need it for messages as well

Cool, added this to #3182.

**Comment by orbitalturtle** [comment]
@valentinewallace Thank you!
