### ISSUE TITLE
Dont abandon payments based on the `payment_id` in an unauthenticated `InvoiceError` message (or any other unauthenticated msg)

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3166]
Filing this to make sure we get it, should be fixed in #3139.

**Comment by jkczyz** [comment]
Doesn't look like #3198 exists.

**Comment by jkczyz** [comment]
We also shouldn't abandon when attempting to pay and erroring with a `Bolt12PaymentError::DuplicateInvoice`.
