### ISSUE TITLE
Blinded Path Selection May Use Tor-Only as Intro Node

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3184]
Bastien tried to pay me and it seems like there were some other issues but our initial thesis was that my node had picked a Tor-Only node as an introduction point and thus they couldn't pay. It looks like we don't filter them and we should (but maybe I missed it).

**Comment by jkczyz** [comment]
Looks like we don't for payment paths though (i.e., in `DefaultRouter::create_blinded_payment_paths`). Somewhat orthogonal: note also that we only filter there; we don't sort like we do in `DefaultMessageRouter`.
