### ISSUE TITLE
Cannot accept value that would put our exposure to tx fee dust at ###### over the limit #### on counterparty commitment tx

### ISSUE THREAD

**Issue by path2727** [lightningdevkit/rust-lightning#3200]
Cannot accept value that would put our exposure to tx fee dust at 2956765 over the limit 2530000 on counterparty commitment tx

I have ldk_node using an electrs server that points to bitciond regtest.  I have an lnd node pointing to different bitciond that is linked to the other.  I try to send funds for lnd node to my ldk_node and I get this error.

I can't receive any payments from my regtest, test node due to this error.  I am not sure how to configure this LDK so that it doesn't happen.  

I opened the channel for lnd to ldk_node like so:

./lncli -n regtest --no-macaroons --lnddir=~/.lnd/  openchannel --node_key XXXXXXXX  --local_amt 10000000  --sat_per_vbyte 1

**Comment by valentinewallace** [comment]
Sorry for the delay. Do you still get this failure if you send a larger payment, like 3-5% of the channel value? It looks like you're sending dust payments (3k sats). If you can list your channels, this field may also be useful: https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelDetails.html#structfield.inbound_htlc_minimum_msat

**Comment by path2727** [comment]
here is my channel details (it is just test data, regtest so don't mind putting it all):

ChannelDetails { channel_id: ChannelId([116, 172, 226, 149, 119, 210, 124, 139, 246, 2, 157, 23, 213, 1, 204, 60, 154, 175, 114, 14, 2, 154, 241, 113, 248, 251, 230, 77, 180, 168, 172, 125]), counterparty_node_id: PublicKey(3c539dd45e55ab1f2645aba1448d7eff1fd4f3e0cf98332d1d62dca403ac5a5f6b097f7c07e36781176c349749e9e3d8e1fbd2181451b35cfe6ad054346cbe49), funding_txo: Some(OutPoint { txid: 0x7daca8b44de6fbf871f19a020e72af9a3ccc01d5179d02f68b7cd27795e2ac74, vout: 0 }), channel_value_sats: 16777000, unspendable_punishment_reserve: Some(167770), user_channel_id: UserChannelId(208156055724322646793064809407019216717), feerate_sat_per_1000_weight: 2500, outbound_capacity_msat: 0, inbound_capacity_msat: 16609230000, confirmations_required: Some(6), confirmations: Some(41), is_outbound: false, is_channel_ready: true, is_usable: false, is_public: true, cltv_expiry_delta: Some(72), counterparty_unspendable_punishment_reserve: 167770, counterparty_outbound_htlc_minimum_msat: Some(1), counterparty_outbound_htlc_maximum_msat: Some(16441460000), counterparty_forwarding_info_fee_base_msat: Some(1000), counterparty_forwarding_info_fee_proportional_millionths: Some(1), counterparty_forwarding_info_cltv_expiry_delta: Some(80), next_outbound_htlc_limit_msat: 0, next_outbound_htlc_minimum_msat: 1, force_close_spend_delay: Some(2015), inbound_htlc_minimum_msat: 1, inbound_htlc_maximum_msat: Some(1677700000), config: ChannelConfig { inner: RwLock { data: ChannelConfig { forwarding_fee_proportional_millionths: 0, forwarding_fee_base_msat: 1000, cltv_expiry_delta: 72, max_dust_htlc_exposure: FeeRateMultiplier(10000), force_close_avoidance_max_fee_satoshis: 1000, accept_underpaying_htlcs: false }, poisoned: false, .. } } }

interesting my minimum is 1 sat it looks like "inbound_htlc_minimum_msat: 1"

my channel has 16777000 satoshis in it

I tested sending 3% and I get the same error

16777000 satoshis * 0.03 = 503310

503 * 1000 = 503310000 msats

invoice with 503310000 msats

lnbcrt5033100n1pn280wudqjv3jhxcmjd9c8g6t0dcnp4q0hrpnn8dq6qehqk7tt56gx36ggec8xfg0z7kavef5nsedvx3cthypp59k4lccfkx92l024eg99lke099hq2t8fqhn5ksqf7w5sttt4qtnzqsp5h7k7ck67krpj686t9esmeyck83wd0pl82vrhc7dr9w85hd3wr0sq9qyysgqcqpcxqr23s4567ukpemkgd45948jpw029vd4tttnnrh9e40q80spqsyts8yuhkuqly40f009ylkx45vpkd3c7j28ssc2ajgqeeeyke0fhe2a8k2dgpd6p92w


I tried to send that invoice and it gave same error

from ldk_node's logs

2024-07-26 15:21:20 TRACE [lightning::ln::peer_handler:1725] Received message UpdateAddHTLC(UpdateAddHTLC { channel_id: ChannelId([116, 172, 226, 149, 119, 210, 124, 139, 246, 2, 157, 23, 213, 1, 204, 60, 154, 175, 114, 14, 2, 154, 241, 113, 248, 251, 230, 77, 180, 168, 172, 125]), htlc_id: 7, amount_msat: 503310000, payment_hash: PaymentHash([45, 171, 252, 97, 54, 49, 85, 247, 170, 185, 65, 75, 251, 101, 229, 45, 192, 165, 157, 32, 188, 233, 104, 1, 62, 117, 32, 181, 174, 160, 92, 196]), cltv_expiry: 18963, skimmed_fee_msat: None, onion_routing_packet: OnionPacket version 0 with hmac [18, 176, 86, 18, 27, 143, 142, 9, 251, 109, 86, 222, 238, 46, 231, 14, 19, 215, 92, 84, 200, 44, 106, 179, 171, 44, 42, 172, 50, 156, 55, 237], blinding_point: None }) from 035f5aac03a4dc621d2d3398cfe0f3d41fff7e8d44a1ab45261fab555ed49d533c
2024-07-26 15:21:20 INFO  [lightning::ln::channel:6183] Cannot accept value that would put our exposure to tx fee dust at 2956765 over the limit 2530000 on counterparty commitment tx

Thanks for your help

**Comment by path2727** [comment]
I tested sending 5% just now as well with same error (838850000msats)

**Comment by path2727** [comment]
I am starting to think I should check my version numbers.... and how it corresponds to your repo.

**Comment by path2727** [comment]
lightning = "0.0.123-beta"

ldk-node = "0.3.0"

**Comment by valentinewallace** [comment]
Ah I misread the error message. I believe this is a feerate disagreement, which tends to crop up in LND<>LDK setups on regtest, i.e. LND's estimated feerates are *much* higher than LDK's and we then count their excess fees towards dust.

@tnull I see you mentioned [here](https://discord.com/channels/915026692102316113/1184952845720617012/1256233875282198588) that this may be fixed in the next LDK release, is that still the case?

**Comment by valentinewallace** [comment]
I think one option is to bump this config option up a ton if you want to try that: https://docs.rs/lightning/latest/lightning/util/config/struct.ChannelConfig.html#structfield.max_dust_htlc_exposure

**Comment by path2727** [comment]
Thanks I'll look into this option to see if it resolves my issue within the next 3-4 days

**Comment by path2727** [comment]
My hack for now to resolve this (it wouldn't let me send from lnd node to rust_lightning on versions 119, 120, 121, 122, 123) is to upon node startup change the channel config like so:

        let channels = node.list_channels();

        for channel in channels {
            let config = channel.config;
            config.set_max_dust_htlc_exposure_from_fixed_limit(80000000000);
            node.update_channel_config( &channel.user_channel_id, channel.counterparty_node_id, config);
        }

This finally let me send $50 worth of satoshis. I coudn't send any amount $100, $200, $10, $1 before I made that change, everything errored with the error mentioned.

I might make the change on the ChannelReady event for newly added channels, but for now this lets me continue to code. I might also look for a more acceptable limit in the future as well.  I am mostly only receiving payments so not sure if this dust thing applies for my case yet.
