### ISSUE TITLE
In-flight amounts get calculated as a part of the per-hop-per-amount penalty when scoring a channel

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3271]
@jkczyz and @wvanlint pointed out that in df52da7b3149 we started applying the in-flight amounts as a part of the per-hop-per-amount penalty which can lead to us strongly avoiding channels that have in-flight funds already. This doesn't make sense as a part of our model, though - the per-hop-per-amount penalty is intended to just provide a per-hop fixed penalty (as there is some per-hop failure probability). It makes sense in the success probability part of our model, though, so we may need to pass the in-flight amount through to the scorer, finally.

**Comment by jkczyz** [comment]
Looking into this, I see that:
- `base_penalty_amount_multiplier_msat` is applied to the payment amount even though the documentation was updated to say to the total amount
- `liquidity_penalty_amount_multiplier_msat` and `historical_liquidity_penalty_amount_multiplier_msat` are applied to the total amount as the documentation states

IIUC, the first just requires reverting the documentation change. The second, however, should only apply to the payment amount. Though the total amount should be used in the `success_probability` calculation.

@TheBlueMatt Does all that sound right?

**Comment by jkczyz** [comment]
> IIUC, the first just requires reverting the documentation change. The second, however, should only apply to the payment amount. Though the total amount should be used in the `success_probability` calculation.
> 
> @TheBlueMatt Does all that sound right?

See #3271 for the proposed fix mentioned above.
