### ISSUE TITLE
Stop Sending ChannelUpdates in onion failures

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3277]
These are optional now, and while other nodes might use them, they shouldn't do so for long (though lnd has said they'll keep using them, but only for fast-retires when they have stale feerate info, which I'm skeptical is common enough for us to care). Removing them would likely reduce a bunch of code.

**Comment by vincenzopalazzo** [comment]
Adding the PR link https://github.com/lightning/bolts/pull/1173 just to make the problem clear. I was looking the code today but I was not able to remember where this change was made.
