### ISSUE TITLE
[Splicing] Add `splicing` compile feature flag

### ISSUE THREAD

**Issue by optout21** [lightningdevkit/rust-lightning#3294]
Introduce a new `splicing` flag (hint: `RUSTFLAGS="--cfg=splicing" ...`). 
The `splicing` flag should be independent of `dual_funding` (they can be used in isolation), but splicing implies the dual funding logic.
Dual funding parts should be surrounded with `any(dual_funding, splicing)`, splicing-only with only `splicing`.
This is in preparation for splicing ( #1621 )
It is a rather mechanical infrastructure change but would make the future splicing PRs cleaner.

Prerequisites: #3137 

Changes can be seen in #3274 , changes of the form `#[cfg(...)]`.

**Comment by jkczyz** [comment]
Already added in #3001.
