### ISSUE TITLE
Score channels on failure/success

### ISSUE THREAD

**Issue by ariard** [lightningdevkit/rust-lightning#482]
Right now we only trace route based on total fee cost. We should be smarter and memorize previous success/failures.

We should pass PaymentSent/PaymentFailed to Router and count them in DirectionalChannelInfo. In the case of PaymentSent every hop should score the success. In the case of PaymentFailed every hop until the failure may be scored the success.

**Comment by sourabhmarathe** [comment]
I'm taking a look at this issue right now
