### ISSUE TITLE
Peer state tracking

### ISSUE THREAD

**Issue by ariard** [lightningdevkit/rust-lightning#486]
We should implement some basic state tracking even if we don't use it now like uptime, flapiness, profitability, htlc volume, ...

They should be store in NodeInfo and be accessible to be used by Router for path-finding, liquidity management, peer management...

**Comment by TheBlueMatt** [comment]
I don't really know how we wnat to do this - I think we need to do a) #432 (which should be relatively simple), then b) add fields for channel/peer reliability, then c) create some Router-ish thing that actively probes the network and updates these fields. CC #106.

**Comment by ariard** [comment]
Yeah that's maybe early to track all of them but you definitely want at least to avoid routing through nodes who are offline and I'm not sure than currently get_route is aware of this.

But thanks for exposing issues on Router, it's a component which need more work for sure and it can go as its own pace because it's not going to interfere with other refactors. Any way to make them more publicly if people want to tackle them ?

**Comment by TheBlueMatt** [comment]
Maybe it makes sense to create a project with all the Router-features/refactors issues tagged in it? I’ll take a look later this week if no one else gets to it.

**Comment by TheBlueMatt** [comment]
Done https://github.com/rust-bitcoin/rust-lightning/projects/4

**Comment by TheBlueMatt** [comment]
We have this now with the `Score` trait and implementors.
