### ISSUE TITLE
Per-Subsystem Logging

### ISSUE THREAD

**Issue by ariard** [lightningdevkit/rust-lightning#687]
While debugging we are most of the time interested about a flow inside a particular module and don't mind observing other RL components. E.g when looking on onchain spending pattern, the commitment building flow doesn't matter.

An improvement on our current logging infrastructure would be to enable subsystem logging through a set of crates features flag, as we're doing for severity. Another enhancement would be tracing protocol objects (onion/commitment transactions/keys)

```
[features]
# Log messages per subsystem
peer_handler = []
channelmonitor = []
channel = []
router = []
transport = []
...
```

Default would be everything.

And you might pass :
`cargo test revoked_output_claim --features channelmonitor`

**Comment by TheBlueMatt** [comment]
I'm a little dubious of the value of having feature flags for everything. It's nice to be able to turn off the most verbose stuff at compile time in production for performance reasons (hence the current feature flags), but module-level filtering could be done in the Logger by examining the arguments pretty trivially.

**Comment by ariard** [comment]
It really depends what you're debugging. If you interested by a flow between ChannelManager/ChannelMonitor a per-data structure is interesting.

Overall, I've spent enough time debugging to feel the need of a per-module flag. Maybe the Logger examining the argument might work as you suggested if it's robust enough.

**Comment by TheBlueMatt** [comment]
The [logger Record structure](https://docs.rs/lightning/0.0.11/lightning/util/logger/struct.Record.html) includes the module, the file path, and the file line, so it should be more than enough for ~anything. The only reason to do it with a feature flag, I think, is performance, which I don't think needs to be that granular.

**Comment by TheBlueMatt** [comment]
Closing as features would be hard to maintain (we already have issues with it) and we expose modules in all languages now IIUC.
