### ISSUE TITLE
[Peers] Feature: Add Channel/Node/Update forwarding

### ISSUE THREAD

**Issue by julianknutsen** [lightningdevkit/rust-lightning#702]
As a message handler, I want to forward certain messages to known initialized peers if the route_handler allows it.

**Definition of Done:**
* Unit tests are updated to include tests that validate message is forwarded to (non-source?) initialized peers for:
  * wire::Message::ChannelAnnouncement
  * wire::Message::NodeAnnouncement
  * wire::Message::ChannelUpdate
* Unit tests exist for the negative case as well when route_handler does not allow it.

**Tech Discussion:**
TODO from the codebase. Similar to the event path, if the route_handler allows it, broadcast the message to all known initialized peers.

Route handler stubs already exist so the testing should be straight forward. A little bit of work to create multiple initialized peers.

Recommend this is done AFTER the unit test work on message handling to get the testing in a better place. Will require a dependency update due to needing an InitializedPeerProvider instead of just the Peer, but should be straight forward.

**Comment by TheBlueMatt** [comment]
Not sure if this was done at the time this issue was opened, but its definitely done now, even with rate-limiting and all the good stuff.
