### ISSUE TITLE
Storage module: integrate LDK with Photon

### ISSUE THREAD

**Issue by moneyball** [lightningdevkit/rust-lightning#778]
Store persistent LN data within Photon server. This requires work on Photon server too. But the general direction of Photon is "store any data associated with a wallet for recovery purposes."

(I don't think this is particularly high priority - more like medium priority but just wanted to document it as it could be a nice, isolated project for a new contributor.)

**Comment by Dasika-Vaishnavi** [comment]
Hi @moneyball, I am Vaishnavi Dasika, I am contributing to Lightning Network Research Organization as a part of Summer of Bitcoin. I am interested in working on this issue.

**Comment by moneyball** [comment]
Hi @Dasika-Vaishnavi, thank you for reaching out! Things have evolved in the past 2+ years since this issue was created. There is now a project called VSS (https://github.com/lightningdevkit/vss-server) that will store wallet data such as LN persisted data. So, I think I'll close this issue. But feel free to look around for other good first issues :) Let us know if there is a particular area you'd like to work on.
